### ISSUE TITLE
Proposal: parameters should not be allowed to automate anything about decoding substreams

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#106]
In the current version of spec, there is mention that parameters may be used to provide time-varying changes to decode, reconstruction, rendering, and mixing.

As we've been tinkering superficially with implementation, it becomes clear that parameters should not affect decoding of substreams.  It should only be applicable to audio element OBUs and mix presentation OBUs (i.e., reconstruction, rendering, and mixing).   I do feel it does not significantly limit the expressive power of the concepts we have.

**Comment by tdaede** [comment]
I think informatively specifying this in the spec is good, but it will also be clear simply because presumably we will have a list of things that can be automated, and there will be nothing audio decoding related in them.

**Comment by tdaede** [comment]
In the current version of the spec we enumerate all parameter possibilities:

```
    if (param_definition_type == PARAMETER_DEFINITION_MIX_GAIN) {
      mix_gain_parameter_data();
    }
    if (param_definition_type == PARAMETER_DEFINITION_DEMIXING) {
      demixing_info_parameter_data();
    }
    if (param_definition_type == PARAMETER_DEFINITION_RECON_GAIN) {
      recon_gain_info_parameter_data();
    }
```

As a a result, there is no room for parameters to affect audio substream decoding.
