### ISSUE TITLE
String encoding is underdefined

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#126]
String formatting and encoding should be defined. In addition, it is unspecified if the string is zero terminated.

**Comment by sunghee-hwang** [comment]
How about UTF-8 encoding with one byte zero terminated?

**Comment by tdaede** [comment]
That will work. A length limit might also be wise.

I do think we need to figure out how exactly this string will be used, also. Will it be shown to the user? Is it expected to be localized?

**Comment by cconcolato** [comment]
The updated SDL spec defines (borrowed from ISOBMFF) the type utf8string as:
> UTF-8 string as defined in IETF RFC 3629, null-terminated.

Also, being able to specify more than one languages would help.

**Comment by sunghee-hwang** [comment]
Let me check this to make it sure.
For a given "label", the encoded bitstream for the string format is composed of as follows:
- 5 bytes ASCII code for two-letter language subtags and two-letter region subtags which are connected by hyphen("-") to indicate the language which the "label" is written in
- And followed by encoded "label" by UTF-8 string as defined in IETF RFC 3629, null-terminated. (Let's call the function it as "UTF-8_Enc")

For example, label = thank you (in us English) then
- 5 bytes ASCII code for "en-us" and followed by UTF-8_Enc(thank you)

For another example, label = 감사합니다 (in korea Korean) then
- 5 bytes ASCII code for "ko-kr" and followed by UTF-8_Enc(감사합니다)

Is it correct?

**Comment by cconcolato** [comment]
My problem is not with the language code. 

One problem is with the "8 x the number of bytes by byte representation of syntaxName.". It misses:
- use of UTF-8
- null-terminated

Another problem is the possibility to give only one language code. One should be able to provide localized labels in several languages.

(BTW "US" and "KR" should be upper case).

**Comment by sunghee-hwang** [comment]
I am not sure if I understand you correctly.
```
string syntaxName

string indicates the type of a string which is terminated by null of one byte (i.e. 0x00).

syntaxName is a human readable label. The byte representation shall consists of two-letter primary language subtags and two-letter region subtags which are connected by hyphen("-"), and followed by bytes representation of label encoded by UTF-8.

```
Where, two-letter primary language subtags and two-letter region subtags shall conform to [[BCP47]](https://aomediacodec.github.io/iac/#biblio-bcp47).

If you have still a problem, would you please implement it to this directly?

**Comment by sunghee-hwang** [comment]
> I am not sure if I understand you correctly.
> 
> ```
> string syntaxName
> 
> string indicates the type of a string which is terminated by null of one byte (i.e. 0x00).
> 
> syntaxName is a human readable label. The byte representation shall consists of two-letter primary language subtags and two-letter region subtags which are connected by hyphen("-"), and followed by bytes representation of label encoded by UTF-8.
> ```
> 
> Where, two-letter primary language subtags and two-letter region subtags shall conform to [[BCP47]](https://aomediacodec.github.io/iac/#biblio-bcp47).
> 
> If you have still a problem, would you please implement it to this directly?

**Comment by sunghee-hwang** [comment]
> Another problem is the possibility to give only one language code. One should be able to provide localized labels in several languages.

I have no idea.  Can you let me know how to do it?

**Comment by sunghee-hwang** [comment]
< One should be able to provide localized labels in several languages.
Regarding this, to support several languages in scope of IAMF, we need to provide several label unless there is a lossless compression method from several labels to one compressed label.
Otherwise, it seems to me that it need to be a scope of an application layer not a scope of IAMF. An application layer, he can decide whether or not he have such an ability to display several languages to users from the language provided by IAMF.
