### ISSUE TITLE
Specify when rule 1 and rule 2 for concatenation are used

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#128]

**Comment by shawnisingh** [comment]
If I understand what this issue means, this should be an encoder choice and so it is only relevant to section 10, right?

In that case, here is some proposed wording:  "Encoder may wish to use Concatenation Rule 1 when combining adjacent segments of the same audio content, while Concatenation Rule 2 may be useful when concatenating different audio programs."

**Comment by sunghee-hwang** [comment]
I think that we need to categorize it into three cases.
- Case 1: The cases which Concatenation rule 1 shall be applied to.
- Case 2: The cases which Concatenation rule 2 shall be applied to.
- Case 3: The cases which either Concatenation rule 1 or rule 2 can be applied to.
