### ISSUE TITLE
Do we need to have the same code for both brand (aiac) and ia_code (iamf)?

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#152]

**Comment by tdaede** [comment]
Specifically this is for renaming the brand to match the new spec name.

**Comment by cconcolato** [comment]
Yes, it is good to align the values.

**Comment by sunghee-hwang** [comment]
In Readme file, it says Immersive Audio Media and Formats. I think it is typo. Media needs to be changed into Model.

**Comment by cconcolato** [comment]
my mistake, I fixed it.
