### ISSUE TITLE
Decide on compatibility for ISOBMFF vs Quicktime versions of AudioSampleEntry (Sound Sample Description)

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#169]
As far as I understand, the syntax for an ISOBMFF v0 AudioSampleEntry is bit compatible with the v0 Quicktime Sound Sample Description.   However, this type of AudioSampleEntry only supports sample rates under 2^16 because the Sample Rate field is a fixed-point 16.16 value.

v1 AudioSampleEntries added a new sampling rate Box, while QuickTime Sound Sample Description v1 added additional required fields - making it incompatible to use the new sampling rate Box for QuickTime.

Possible solution - we should try to require a v0 AudioSampleEntry that works for both QuickTime and ISOBMFF.  If we need to express higher sample rates, it's unclear how to be compatible, and we may need to define this syntax separately for ISOBMFF and for Quicktime.

**Comment by tdaede** [comment]
We now use IA_Descriptor sample entries. This is no longer needed.

Secondly, we currently don't specify quicktime brands, only ISOBMFF ones.
