### ISSUE TITLE
Better use of "shall"

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#170]
The use of "shall" should be reserved to cases where the subject is a bitstream or a construct and the corresponding statement can be verified/validated. In other words, if there is a "shall" it should be possible to create a bitstream/file that is valid against the shall and another bitstream/file that is invalid against the "shall". There could also be cases where "shall" applies to a reader.

The current draft uses "shall" for rules that cannot be verified because they are definitions or statement of facts on the spec.
Examples:
> All of syntax elements shall conform to SDL
This should simply be:
> All of syntax elements conform to SDL

Another example:
> OBU data shall start on the first (most significant) bit and shall end on the last bit of the given bytes. The payload of an OBU shall lie between the first bit of the given bytes and the last bit before the first zero bit of the byte_alignment().
This is by definition. The payload of an OBU is the data between the first and last byte excluding the header. I would remove shall or even remove the entire paragraph.

> obu_size shall indicate the size in bytes
Again a statement of fact. Use "indicates".

There are many other occurrences. A pass on the spec should be done.

**Comment by sunghee-hwang** [comment]
It would be better to take this action after most of the spec texts are cleared.
