### ISSUE TITLE
gapless is not defined

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#177]
The word `gapless` is used 3 times but never formally defined.  For example, it says:
> For this version of the specification, all audio frames for a given substream must be gapless.

How can it be otherwise? Isn't it by definition: the audio processors takes audio frames one after the other (possibly applying trimming) but since there is no duration field in the header, there can be no gap, and no overlap.

I would suggest removing the sentence here. Adding a clarification in 3.1 that an audio substream is the concatenation of all its audio frames in order.

Similarly, the spec says:
> Between two Sync OBUs, a sequence of audio frames or parameter blocks must be gapless.

I don't understand how it could be otherwise. I suggest deleting the sentence and the other similar one.

(Also, the spec uses "must" 15 times. It probably should be "shall")

**Comment by cconcolato** [comment]
I still think we should not introduce the word "gapless". It's creating more confusion than helping IMHO.

**Comment by sunghee-hwang** [comment]
Do you assume that substreams has no gap unless we define a subsream with a gap?
So, do you think that v1 does not need to define gapless because v1 does not allow a gap?

**Comment by cconcolato** [comment]
> Do you assume that substreams has no gap unless we define a subsream with a gap?

yes, that's my understanding.

> So, do you think that v1 does not need to define gapless because v1 does not allow a gap?

IMO, it should neither define nor use the term gapless.

**Comment by sunghee-hwang** [comment]
Let me revisit this after the issues related to sync obu are cleared.
