### ISSUE TITLE
Clarify quadratic interpolation equation in animated parameters

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#223]
See discussion on: https://github.com/AOMediaCodec/iamf/pull/222#discussion_r1057020711

**Comment by tdaede** [comment]
Specifically, the 2D coordinates seem to be used as scalar values inside the equations.

**Comment by felicialim** [comment]
Let `B_quad(a) = (x, y)`. And from the spec, 

```
P0 = (t_start, start_point_value),
P1 = (t_control, control_point_value),
P2 = (t_end, end_point_value),
B_quad(a) = (1 - a)^2 * P0 + 2 * (1 - a) * a * P1 + a^2 * P2
```

The multiplications in B_quad(a) are element-wise multiplication between the scalar value `a` and the 2D coords P0, P1, P2. Then we have

`x = (1 - a)^2 * t_start + 2 * (1 - a) * a * t_control + a^2 * t_end`

`y = (1 - a)^2 * start_point_value + 2 * (1 - a) * a * control_point_value + a^2 * end_point_value`

**Comment by tdaede** [comment]
OK, that works. I do think a definition in terms of (x) might be more straightforward, as I'd expect that's what would directly appear in most implementations.

**Comment by sunghee-hwang** [comment]
Thanks for clarification. I think that we need to clarify more for decoders how to do by using these equations.
For example, for audio samples of a given segment, how to get the output sample values after applying this?
