### ISSUE TITLE
Optimized order of descriptor OBUs

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#232]
In Mix Presentation OBU, the rendering_config() has used audio element type already:
But Mix Presentation OBU's order is currently before Audio Eelement OBU, so we can not know audio element type until reading Audio Element OBU.
[As Is]
1. One Magic Code OBU
2. All Codec Config OBUs
3. All Mix Presentation OBUs
4. All Audio Element OBUs

[To Be]
1. One Magic Code OBU
2. All Codec Config OBUs
3. All Audio Element OBUs
4. All Mix Presentation OBUs

**Comment by tdaede** [comment]
Fixed by #235
