### ISSUE TITLE
Need to add down-mix matrices to 3.1.2ch: libear does not support 3.1.2ch as output

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#237]
Unless demixing_info_parameter_data is delivered, there is no way to down-mix to 3.1.2ch from channel audio with height channels because libear does not support 3.1.2ch output.
So, we need 4 down-mix matrices at least
- From 7.1.4ch to 3.1.2ch down-mix matrix
- From 7.1.2ch to 3.1.2ch down-mix matrix
- From 5.1.4ch to 3.1.2ch down-mix matrix
- From 5.1.2ch to 3.1.2ch down-mix matrix

**Comment by tdaede** [comment]
We need to double-check libear support.

**Comment by sunghee-hwang** [comment]
https://github.com/ebu/libear/issues/51
