### ISSUE TITLE
Opus Channel Count can be set to 1 or 2

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#246]
Section 4.3.1 states "Channel Count should be set to 2." 
This can be relaxed to 1 or 2 for mono substreams.

**Comment by sunghee-hwang** [comment]
You are right. It can be set to 1 or 2. 
But, Group has decided to select one of them it as we have only one decoder_config.
So, the spec has following description in Section 7.2.4.1.
```
'OutputChannelCount' can be ignored because the real value can be determined from the Audio Element OBU and from the 'opus packet' header.
```
I think the similar description needs to be added in Section 4.3.1.

**Comment by felicialim** [comment]
Thanks, good point
