### ISSUE TITLE
Consider removing fields from Opus Config / analyze how we require existing fields to be set

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#256]
We use almost none of the data inside the Opus Config. We should investigate if byte compatibility with the Opus specific config in ISOBMFF is still important, and also look at the exact restrictions we place on the config.

**Comment by sunghee-hwang** [comment]
I think that the data inside the Opus Config should be kept to be compatibility with the Opus specific config in ISOBMFF as long as we use the same name ('dOps') of OpusSpecificBox as that of OPUS-ISOBMFF.

**Comment by sunghee-hwang** [comment]
It should be closed because we have already decided that descriptor OBUs are moved to SampleEntry which has been merged.

**Comment by sunghee-hwang** [comment]
It is closed as issue #259 is already resolved.
