### ISSUE TITLE
LPCM needs packing definitions and/or to be limited to fixed sample sizes

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#257]
We need to specify packing and endianness (possibly by citing an existing reference). This is much simpler if samples are limited to fixed sizes (e.g. 16-bit and 24-bit).

**Comment by sunghee-hwang** [comment]
Section 10 in the current IAMF spec guides 16-bit or 24-bit sample size and wav files as input audio format.
Samples in wav file are stored in little-endian byte order. 

In section 4.1.10, we have following description.
```
For IAMF-LPCM, 'audio_frame()' shall be LPCM samples. When more than one byte is used to represent a LPCM sample, the byte order shall be in little endian.
```

But, we normally use network byte order (big-endian) for delivery (including ISOBMFF packing).

It may be changed into 
```
For IAMF-LPCM, 'audio_frame()' shall be LPCM samples. When more than one byte is used to represent a LPCM sample, the byte order shall be in big endian.
```
to make "ipcm" in #258 be able to wok. (It seems to me that "ipcm" uses big-endian byte order.)
