### ISSUE TITLE
LPCM Codec config string needs to be ipcm or fpcm

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#258]
In section 7.4:
```
    For IAMF-LPCM

iamf.IAMF-specific-needs.lpcm
```
This needs to be ipcm or fpcm (integer or float). Currently our spec supports only integer pcm, so we should change it to ipcm (unless we want to add float support).

**Comment by sunghee-hwang** [comment]
It seems to me that "ipcm" uses big-endian byte order. Is it correct?

**Comment by shawnisingh** [comment]
Can you please refer to the spec document where ipcm and PCM in general are spec'd for ISOBMFF?  I'm only familiar with Quicktime's version.  I'm curious how ISOBMFF integration of PCM differs from Quicktime's.  For one, I didn't think that Quicktime supported a fourcc of "ipcm", I thought it was only "lpcm" according to https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html

Thanks!

**Comment by shawnisingh** [comment]
As another example of looking for information, I also did not see any place where ffmpeg uses the fourcc "ipcm".  Does anyone know if it's supported, and which avformat module to look at in ffmpeg?   It's not in mov.c as far as I could tell.

**Comment by sunghee-hwang** [comment]
ISO/IEC 23003-5 uncompressed audio in MP4 file format.
