### ISSUE TITLE
Consider reducing/eliminating the need for bitstream copies during unpacking from ISOBMFF (via sample groups)

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#259]
Currently, when demuxing, the sample groups in 7.2.6 require copying OBUs out of the group and into the stream. This is difficult or inefficient for some implementations (e.g. a full-featured HW implementation).

We should consider alternate options to these sample groups. For example, multiple sample entries for 7.2.6.1.

We should also double check that ISOBMFF allows information in sample groups to be required for decoding.

**Comment by sunghee-hwang** [comment]
It is closed as it is already resolved.
