### ISSUE TITLE
Consider to restrict the combinations of two audio elements with the same element types.

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#267]
- Do we need a base profile with Ambisonics + Ambisonics?
- Do we need a base profile with Scalable (num_layers > 1) + Scalable (num_layers > 1)?

IMO, 
- It shall be at most one Ambisonics at any one time in base profiles.
- It shall be at most one Scalable audio (num_layers > 1) at any one time in base profiles.

**Comment by felicialim** [comment]
Just to check, does this mean that the allowed combinations would be:

1. Ambisonics + scalable (num_layers > 1)
2. Ambisonics + scalable (num_layers == 1)
3. Scalable (num_layers > 1) + scalable (num_layers == 1)
4. Scalable (num_layers == 1) + scalable (num_layers == 1)

**Comment by sunghee-hwang** [comment]
Yes. You are correct.

**Comment by felicialim** [comment]
Sounds good.
