### ISSUE TITLE
Need to clarify who will trim during decapsulation of ISOBMFF file.

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#271]
During encapsulation into ISOBMFF, trimming information will be reflected to the relevant boxes according IAMF specification.
Meanwhile, Some samples have trimming information when audio frame OBUs have trimming data.
Then who should trim the data during decapsulation of IAMF-ISOBMFF file? IAMF decoder or IAMF-ISOBMFF parser

**Comment by tdaede** [comment]
We will do track level trimming via ISOBMFF edit lists. The information will be copied from bitstream level trimming (see e.g. Opus in ISOBMFF mapping). The Simple and Base profiles will be restricted such that start times / trimming are the same to make this a simple process.

**Comment by sunghee-hwang** [comment]
'start times' means start PTS? 
In terms of AV synchronization, when we assume 10ms audio pre-amble and no video pre-amble, which values are set to audio start PTS and video start PTS when each es stream is passed to the decoder?
- audio start PTS and video start PTS = 0 ?
- audio start PTS = -10ms and video start PTS = 0 (or audio start PTS =0 and video start PTS = 10ms)?
I would like to understand what the conventional behaviours are.
Please teach me!

**Comment by sunghee-hwang** [comment]
How about this?
It is not perfect figures but it shows trimming related procedures.
NOTE: IAMF Decoders for both Standalone and ISOBMFF Interlocked shall do trim audio samples to be trimmed in mid-stream (in case of shore-lived audio elements which neither start nor end at start or end of the stream)

[Standalone-IAMF Decoder]
```mermaid
graph TD
OBU_Parser(OBU Parser) --> |PTS1| Substream_Decoder("Substream Decoder")
OBU_Parser --> |Substreams| Substream_Decoder
Substream_Decoder --> |PTS1| Mix_Presentation("Mixing and Presentation")
OBU_Parser --> |Trimming Information| Mix_Presentation
Substream_Decoder --> |Audio Samples before trimming| Mix_Presentation
Mix_Presentation --> |Audio Samples after trimming at PTS2| Speakers 
```

[ISOBMFF Interlocked]
```mermaid
graph TD
ISOBMFF_Parser(ISOBMFF Parser) --> |Descriptor OBUs| IAMF_Decoder("IAMF Decoder")
ISOBMFF_Parser(ISOBMFF Parser) --> |PTS1| IAMF_Decoder("IAMF Decoder")
ISOBMFF_Parser --> |Samples| IAMF_Decoder
IAMF_Decoder --> |PTS1| OBU_Parser(OBU Parser) 
IAMF_Decoder --> |Samples| OBU_Parser(OBU Parser)
OBU_Parser --> |PTS1| Substream_Decoder("Substream Decoder")
OBU_Parser --> |Substreams| Substream_Decoder
Substream_Decoder --> |PTS1| Mix_Presentation("Mixing and Presentation")
Substream_Decoder --> |Audio Samples before trimming| Mix_Presentation 
Mix_Presentation --> |PTS1| ISOBMFF_Player
ISOBMFF_Parser --> |Trimming Information| ISOBMFF_Player 
Mix_Presentation --> |Audio Samples before trimming| ISOBMFF_Player 
ISOBMFF_Player --> |Audio Samples after trimming at PTS2| Speakers 
```

**Comment by sunghee-hwang** [comment]
How about this option?

During trying to resolve this issue, I have realized that the inputs, which IAMF decoders get, are same as both IAMF parser or IAMF-ISOBMFF parser would pass descriptor OBUs, PTS and Samples (or Temporal Units) to IAMF decoders. 

NOTE: IAMF Decoder needs to trim audio samples to be trimmed at the end of substreams which do not end at the end of the the stream and at the start of substreams which do not start at the start of the stream. 

```mermaid
graph TD
Parser("IAMF Parser <br> (or IAMF-ISOBMFF Parser)") --> |Descriptor OBUs| IAMF_Decoder("IAMF Decoder")
Parser --> |PTS1| IAMF_Decoder
Parser --> |Samples or Temporal Units| IAMF_Decoder
IAMF_Decoder --> |PTS1| Player
IAMF_Decoder --> |Audio Samples before trimming| Player("IAMF Player or ISOBMFF Player")
Parser --> |Trimming Information| Player
Player --> |Audio Samples after trimming starting at PTS2| Speakers("Loudspeakers") 
```

**Comment by tdaede** [comment]
Hi, sorry for the late reply on this, but these first diagrams look fine. The only confusing thing wrt the diagrams is that I think they would be improved if they explicitly showed the two paths for trimming when in ISOBMFF for start/end or middle, or had two separate diagrams, one for each.

For the last diagram, I'm not 100% clear on it. Are you saying in this special case, the decoder would do all the trimming, and edts would reflect zero trim? Or would this be all the time, and not just in the special case?

**Comment by sunghee-hwang** [comment]
Based on the current Ref. S/W dec operation, we have realized that the below figures would be more appropriate, 
PTS1: Start Presentation Time Stamp before trimming (i.e. PTS of the first audio sample)
PTS2: Start Presentation Time Stamp after trimming (i.e. PTS of the first audio sample)
PTS: PTS1 or PTS2

IAMF decoders output PTS and audio samples. 
For IAMF-ISOBMFF Player (ISOBMFF Inter-locked player), IAMF decoders may or may not trim the data but they output audio samples and its start PTS.
For IAMF Player (standalone player), IAMF decoders trim the data. In other word, they output PTS2 and audio samples after trimming.

[ISOBMFF Inter-locked IAMF Player]
```mermaid
graph TD
Parser("IAMF-ISOBMFF Parser") --> |Descriptor OBUs| IAMF_Decoder("IAMF Decoder")
Parser --> |PTS1| IAMF_Decoder
Parser --> |Samples or Temporal Units| IAMF_Decoder
IAMF_Decoder --> |PTS & Audio Samples| Player("IAMF-ISOBMFF Player")
Parser --> |PTS1 & Trimming Information| Player
Player --> |Audio Samples after trimming starting at PTS2| Speakers("Loudspeakers") 
```
[Standalone IAMF Player]
```mermaid
graph TD
Parser("IAMF File Parser") --> |Descriptor OBUs| IAMF_Decoder("IAMF Decoder")
Parser --> |PTS1| IAMF_Decoder
Parser --> |Samples or Temporal Units| IAMF_Decoder
IAMF_Decoder --> |PTS2 & Audio Samples after timming| Player("IAMF File Player")
Player --> |Audio Samples after trimming starting at PTS2| Speakers("Loudspeakers") 
```

**Comment by sunghee-hwang** [comment]
Hi Shawn, 

As discussed at the IAMF call, please share your note for the standalone IAMF player.
Here is a draft note from my side. Please review and update it if needed.
NOTE: It may be a third entity to manage AV synchronization, in this case the third entity may provide PTSs for the synchronization so that the figure for [Standalone IAMF Player] needs no PTSs.
