### ISSUE TITLE
Ensure that FLAC config matches FLAC-in-ISOBMFF config box

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#273]
https://gitlab.xiph.org/iemaghni/flac/-/blob/823c65608a7244abdbc8df5953fc54f8f1f8cc2c/doc/isoflac.txt

**Comment by sunghee-hwang** [comment]
The current IAMF WD says that
"[Decoder_Config()] for IAMF-FLAC is [METADATA_BLOCK] of [[FLAC]]."

METADATA_BLOCK is the same as FLACMetadataBlock specified in https://gitlab.xiph.org/iemaghni/flac/-/blob/823c65608a7244abdbc8df5953fc54f8f1f8cc2c/doc/isoflac.txt.

**Comment by sunghee-hwang** [comment]
It is closed as it is already implemented in the WD
