### ISSUE TITLE
Improve Mix Presentation OBU human-readable annotation fields

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#290]
This probably will need more discussion from others to flesh out. But here are some initial thoughts / suggestions:

1. These should be some form of unicode (probably UTF-8) to support human-readable strings in languages that have non-ascii characters.
2. We should consider cases where streams would be merged. Submixes could be combined together. What happens to annotations? Also do we need more than 1 substream in simple / base profile?
3. We should break out useful "dimensions" in the `mix_presentation_annotations` and `mix_presentation_element_annotations` class defined in the spec.
4. Add a section to recommend displaying these fields as appropriate to the user.
5. Consider which portions need annotations (mix, submix audio element, submix). Currently only the former 2 have annotations.

Potential ideas for separate fields within the `*_annotations` classes.
- Language Code
- Channel layout (or maybe not because this would be duplicate information and annotations should just be informative)
- Content type an enum or a string (commentary, audio, dialogue, music, ...). I think there is an ISOBMFF field we could get inspriation from.
- Mix rank (lowest rank is tiebreaker as a "default")
- Potentially other fields or put some room in here for extensibility?

**Comment by cconcolato** [comment]
Related to #404

**Comment by sunghee-hwang** [comment]
Closed by PR #832.
