### ISSUE TITLE
Align PCM and FLAC supported bit depths

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#295]
Make sure LPCM and FLAC support the same bit depth formats inside IAMF.

**Comment by sunghee-hwang** [comment]
Copied from https://xiph.org/flac/format.html.

- METADATA_BLOCK_STREAMINFO
<html>
<body>


<5> | (bits per sample)-1. FLAC supports from 4 to 32 bits per sample.
-- | --



</body>
</html>

- FRAME_HEADER

<3> Sample size in bits: 
 000 : get from STREAMINFO metadata block
 001 : 8 bits per sample
 010 : 12 bits per sample
 011 : reserved
 100 : 16 bits per sample
 101 : 20 bits per sample
 110 : 24 bits per sample
 111 : 32 bits per sample

**Comment by tdaede** [comment]
Looks like they match up then. It's worth noting though that the official libflac implementation only added 32 bit support as recently as Sep 2022: https://xiph.org/flac/2022/09/09/flac-1-4-0-released.html
