### ISSUE TITLE
OBU header for Magic Code OBU should be "0xF807"

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#304]
Currently it's stated "the obu header (2 bytes) shall be set to `0xF006`" (§[4.1.5](https://aomediacodec.github.io/iamf/#obu-magiccode)), but the correct 2 bytes should be `0xF807`.

`0xF8` comes from:
```
    obu_type | redundant | trimming | extension
    11111      0           0          0
```
`0x07` comes from the payload size being 6 bytes, plus one byte to record the `obu_size` itself.

**Comment by jwcullen** [comment]
Agree, but additionally the wording should reflect that it could also be 0xFC07. The redundant copy flag should be set when additional copies are inserted.
