### ISSUE TITLE
Fix the bug in loudness_info()

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#323]
when info_type = 0, the true peak is defined. But the implemented code is wrong.
if (info_type & 1) {
    signed int (16) true_peak;
}
It should be changed to
if (info_type == 0) {
    signed int (16) true_peak;
}

**Comment by jwcullen** [comment]
I was reading this as a bitmask. I was imagining in the future it was implemented this way to allow the mask to multiple other types of loudness like below. And the current wording may be good for forwards compatibility.

```
// Check if bit 0 is set to include the true peak.
 if (info_type & 1) {
    signed int (16) true_peak;
  }
  
// Check if bit 1 is set to include 1st new measurement.
  if (info_type & 2) {
    signed int (16) new_loudness_measurement_1;
  }

// Check if bit 2 is set to include 2nd new measurement.
  if (info_type & 4) {
    signed int (16) new_loudness_measurement_2;
  }

...
// Check if bit 7 is set to include the 7th new measurement.
  if (info_type & 128) {
    signed int (16) new_loudness_measurement_7;
  }
```

Also note how this wording reserves bits 1 - 7 and defines bit 0. It is not reserving 1 - 255.

```
info_type is a bitmask that specifies the type of optional loudness information provided. The bits are set as follows, where the first bit is the LSB:

Bit : Type of information provided
 0  : True peak
1~7 : Reserved
```

**Comment by sunghee-hwang** [comment]
Thank you for correcting me. I misunderstood it.
Let me close this issue.
