### ISSUE TITLE
Fix issue with duplicate parameter_ids

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#334]
Should the `parameter_id` field in [ParamDefinition](https://aomediacodec.github.io/iamf/#parameter-definition) always be unique?

Otherwise I think that `get_param_definition` defined in [Parameter Block OBU](https://aomediacodec.github.io/iamf/#obu-parameterblock) would not be able to find the correct information if there were multiple `ParamDefinition`s with different IDs.

I see some text in [§10.2.7.1](https://aomediacodec.github.io/iamf/#iamfgeneration-multipleaudioelements-onecodec) that mentions they should be unique. But as it is worded it does not mention uniqueness among parameters within a Mix Presentation OBU or even if multiple parameters within an Audio Element OBU.

**Comment by sunghee-hwang** [comment]
I think that parameter_id shall be unique to identify its parameter blocks carrying parameter values. However, the same ParamDefinition for the parameter_id can present in multiple places in case of that for example the same element_mix_config is applied to multiple audio elements or both element_mix_config and output_mix_config defines the same parameter values.
