### ISSUE TITLE
DecoderConfigDescriptor for AAC is different in the 14496-1:1998 and 14496-1:2010

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#338]
The old version of DecoderConfigDescriptor has a length field that is absent in the new version. We should pick one of the versions to use for our spec.

Youtube uses the old version. We should investigate ffmpeg (or other projects') parsers to see if they support both versions. If support for the new version is widespread we should pick version, but if it was never widely adopted we should go with the old version.

**Comment by cconcolato** [comment]
[14496-1 4th/2010 edition](https://www.iso.org/standard/55688.html) contains:
```
abstract aligned(8) expandable(228-1) class BaseDescriptor : bit(8) tag=0 {
	// empty. To be filled by classes extending this class.
}
class DecoderConfigDescriptor extends BaseDescriptor : bit(8) tag=DecoderConfigDescrTag {
	bit(8) objectTypeIndication;
	bit(6) streamType;
	bit(1) upStream;
	const bit(1) reserved=1;
	bit(24) bufferSizeDB;
	bit(32) maxBitrate;
	bit(32) avgBitrate;
	DecoderSpecificInfo decSpecificInfo[0 .. 1];
	profileLevelIndicationIndexDescriptor profileLevelIndicationIndexDescr [0..255];
}
```

It seems that the 2001 version (http://netmedia.zju.edu.cn/multimedia2013/mpeg-4/ISO%20IEC%2014496-1%20MPEG-4%20System%20Standard.pdf) has the same syntax.

I don't have a copy of the 1998 version. Can you post a snippet of it?

**Comment by tdaede** [comment]
We are using the version specified in the specification.
