### ISSUE TITLE
Parameters should not have non-integer (fractional) segment intervals

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#352]
In the current spec, there are no restrictions on the relationship between parameter's duration, num_segments, and the sum segment_intervals.

For example, with constant segment intervals, it is possible to have:
duration = 960
num_segments = 25
Then, the duration of each segment would be 38.4

And with non-constant segment intervals, there is no explicit restriction that:
"duration == sum(segment_interval)" must be true.

I think it will be natural for implementations to assume that beginning and ends of parameter blocks will line up with integer numbers of ticks in the parameter's own time base.   If a parameter needs higher precision for any reason, the parameter's rate can be increased, so that ticks have a finer resolution.

With all this in mind, I would propose that we explicitly restrict the relationship between duration, num_segments, and sum(segment_intervals) to ensure that each segment has an integer duration.

**Comment by sunghee-hwang** [comment]
Please refer to the section for Parameter Definition. I think that the section is already addressing your concern.



constant_segment_interval specifies the interval of each segment, in the case where all segments except the last segment have equal intervals. If all segments except the last segment do not have equal intervals, the value of constant_segment_interval shall be set to 0.

segment_interval specifies the interval for the given segment. 

Each value of [duration](https://aomediacodec.github.io/iamf/#duration), [constant_segment_interval](https://aomediacodec.github.io/iamf/#constant_segment_interval) and [segment_interval](https://aomediacodec.github.io/iamf/#segment_interval) shall be expressed as the number of ticks at the [parameter_rate](https://aomediacodec.github.io/iamf/#parameter_rate) specified in the corresponding parameter definition.

When it defines D = the value of [duration](https://aomediacodec.github.io/iamf/#duration), NS = the value of [num_segments](https://aomediacodec.github.io/iamf/#num_segments), CSI = the value of [constant_segment_interval](https://aomediacodec.github.io/iamf/#constant_segment_interval) and SI = the value of [segment_interval](https://aomediacodec.github.io/iamf/#segment_interval).

When [CSI](https://aomediacodec.github.io/iamf/#csi) != 0, [NS](https://aomediacodec.github.io/iamf/#ns) x [CSI](https://aomediacodec.github.io/iamf/#csi) shall be equal to or greater than [D](https://aomediacodec.github.io/iamf/#d).

If [NS](https://aomediacodec.github.io/iamf/#ns) x [CSI](https://aomediacodec.github.io/iamf/#csi) > [D](https://aomediacodec.github.io/iamf/#d), the actual interval of the last segment shall be [D](https://aomediacodec.github.io/iamf/#d) - ([NS](https://aomediacodec.github.io/iamf/#ns) - 1) x [CSI](https://aomediacodec.github.io/iamf/#csi).

When [CSI](https://aomediacodec.github.io/iamf/#csi) = 0, the summation of all [SI](https://aomediacodec.github.io/iamf/#si)s in this parameter block shall be equal to [D](https://aomediacodec.github.io/iamf/#d).

**Comment by sunghee-hwang** [comment]
I think that this issue needs to be cloased because the current WD already is implementing it.

**Comment by tdaede** [comment]
@shawnisingh I am closing this issue, reopen it if it is still a problem.
