### ISSUE TITLE
Suggest renaming parameter "segment" and "segment_interval"

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#353]
The word segment may become overloaded with the idea of DASH segments.

Would it make sense to call it a subblock instead?   i.e. a parameter block may have 1 or more subblocks that define actual values of the parameter over time.

And further, instead of "segment_interval" -> this really is "duration", I feel that interval would be two values describing a beginning point and end point, with questions about semantics of open/closed boundaries.   So would it make sense to rename this to "subblock_duration"?

**Comment by sunghee-hwang** [comment]
I think that it makes sense.
