### ISSUE TITLE
Contradicting (or at least confusing) where Sync OBUs are allowed

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#367]
In [5.1.2](https://aomediacodec.github.io/iamf/#standalone-descriptor-obus):
"A new Sync OBU may be inserted anywhere in the sequence of data OBUs, as frequently as needed."

In [4.1](https://aomediacodec.github.io/iamf/#profiles-simple) and [4.2](https://aomediacodec.github.io/iamf/#profiles-base):
"There shall be only one Sync OBU placed immediately after each set of Descriptor OBUs, and no additional new Sync OBUs inserted anywhere in the sequence of data OBUs that follow."

**Comment by jwcullen** [comment]
Another mention of Sync OBUs that is related and contributes to the confusion is described in §[11.2](https://aomediacodec.github.io/iamf/#annex-b-short-lived-audio):
"The second method uses Sync OBUs, without requiring a new Mix Presentation OBU. The Mix Presentation OBU contains an Audio Element OBU for each of A and B, and a Mix Presentation OBU that references both A and B. The first Sync OBU placed immediately after the Mix Presentation OBU includes both A and B. When the audio element B has ended, a new Sync OBU is placed in the IA stream which includes only A, indicating that B is no longer present in the timeline that comes immediately afterwards."

**Comment by jwcullen** [comment]
Section 5.1.2 and 11.2 are out of date.
