### ISSUE TITLE
Clearly mark informative sections / comments

### ISSUE THREAD

**Issue by jzern** [AOMediaCodec/iamf#368]
At c9595f359174c44dbcf7d4d7f996b8469454274c, sections like 9 and 10 are given as examples, but could make this a bit more clear by using 'informative' in the prose or the section header with `(Informative)` for instance.

**Comment by tdaede** [comment]
This came up in #377 as a restriction seems to only appear in 9 and 10.

I believe 9 and 10 are actually intended to be normative. We need to change their wording and evaluate them in this context.

**Comment by jzern** [comment]
In other discussions between @yeroro and @sunghee-hwang they sounded like they concluded in the other direction. If there are decoder restrictions then they certainly should be normative. Any text referring to a sample encode process doesn't have to be, as implementations can vary, just the final bitstream needs to follow the recommendations.
