### ISSUE TITLE
Clarify how to implement multiple sample entries into ISOBMFF file

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#371]
We have updated to support multiple sample entries instead of sample group. 
However, it may face to interoperability issue unless we define a specific implementation way.

Here is IMHO.
- ISOBMFF Encapsulation of multiple sample entries can be done in the same way as that of single sample entry except following restrictions:
1. data_reference_index in each sample entry of 'stsd' box shall be set to 1 for all sample entries of 'stsd' box.

   : 'dref' box has one single data entry for 'url ' (refer to that of https://opus-codec.org/docs/opus_in_isobmff.html)
   : There will be only one 'mdat' box for non-fragmented files like that of single sample entry.
2. [For non-fragmented files] Each entry of 'stsc' box indicates its associated sample_description_index. From this, parers can know its start chunk and the number of chunks for each sample entry.
3. [For fragmented files] Each 'tfhd' box indicates its associated sample_description_index. From this and 'trun', parsers can know the location of samples which are identified by the sample_description_index.

**Comment by cconcolato** [comment]
The restriction regarding `data_reference_index` is interesting (it is an actual restriction in CMAF) but it is not directly related to single vs multiple sample entries. I think it should be dealt with, separately. I'm fine with adding this restriction if the group wants to.

The number of `mdat` box is another issue. Irrespective of dref, or of fragmentation, or of sample entries, a file writer can decide to use many `mdat`. The spec should be silent about it.

Regarding single vs multiple sample entries, as you indicate, ISOBMFF indicates for each sample (in fragmented or non-fragmented case) which sample entry to use. I put some comments in #403 regarding when multiple sample entries are needed: basically, when different config OBUs need to be associated with different samples. The spec should say that it's possible and that implementations should support it.

**Comment by sunghee-hwang** [comment]
> The restriction regarding `data_reference_index` is interesting (it is an actual restriction in CMAF) but it is not directly related to single vs multiple sample entries. I think it should be dealt with, separately. I'm fine with adding this restriction if the group wants to.
> 
> The number of `mdat` box is another issue. Irrespective of dref, or of fragmentation, or of sample entries, a file writer can decide to use many `mdat`. The spec should be silent about it.
> 
> Regarding single vs multiple sample entries, as you indicate, ISOBMFF indicates for each sample (in fragmented or non-fragmented case) which sample entry to use. I put some comments in #403 regarding when multiple sample entries are needed: basically, when different config OBUs need to be associated with different samples. The spec should say that it's possible and that implementations should support it.

**Comment by sunghee-hwang** [comment]
@cconcolato, 

Thank you for your information.

Generally, I can agree with for our spec to be silent about the number of `mdat` regardless of one single entry or multiple sample entires. 
However, I have thought that we need to secure interoperability issue may be caused by losts of implementation ways of multiple sample entries. I have been heard that the industry have not been implementing multiple sample entries.

So, I made such a draft proposal to secure the potential interoperability issue caused by lots of implementation ways of multiple sample entries, by restricting the implementation of multiple sample entries to only one way.
