### ISSUE TITLE
Solve how parameter blocks can properly align with trimmed audio frames

### ISSUE THREAD

**Issue by shawnisingh** [AOMediaCodec/iamf#375]
Parameter blocks do not have a notion of "trimming".  It is unclear how parameter blocks should realign with audio when there is trimming present in an audio substream.  One possibility is that we can rely on Sync OBU relative offset to convey alignment information. We need to think through how timing representation works pre-trimming and post-trimming.

**Comment by sunghee-hwang** [comment]
@shawnisingh and @tdaede,

Parameters will be generated for a given raw audio samples. So when we assume the sampling rates are same, then the total number of the parameter values would be same the total number of the given raw audio samples.

So, I think that we should start from this baseline. If you agree with this.
The total duration of Parameter Block OBUs shall be same as the total duration of the output audio frames after trimming.
If the trimming at start presents for the substream, then the exact sync point between the substream and the parameter is indicated by `relative_offset`s in Sync OBU.

In random access point of view, 
when we access a random access point, if the associated substream has been trimming data at start, the actual audio sample for the start composition time of the random access point is not the first audio sample of the random access point but the first audio sample after discarding as many audio samples as MOD(the amount of trimming data, num_samples_per_frame) from the start of the random access point.

IMHO, it seems that the current spec works well. But, we may need to add the context of the last sentence above in our specification to clarify it.

**Comment by sunghee-hwang** [comment]
Addressed by issue #415.

**Comment by sunghee-hwang** [comment]
It is closed as PR #415 is merged
