### ISSUE TITLE
Bezier curve control may be too granular

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#380]
I do not have anything concrete to show, but maybe `control_point_relative_time` [section 3.9.1](control_point_relative_time) should be more than 8 bits? Intuition is telling me that only 256 values here could be too granular.

**Comment by tdaede** [comment]
The resolution limit can be mitigated by splitting into smaller parameter blocks. For optimal bitrate, the best size of control_point_relative_time depends on the typical bezier curves and resolution expected.

**Comment by sunghee-hwang** [comment]
It is closed as the comment has been resolved.
