### ISSUE TITLE
Clarify the scope of uniqueness meant by "unique obu_id"

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#382]
There are several sentences in the Spec like this
"xxx id indicates an unique obu_id with obu_type = yyy". Does it mean:

1. IDs within a particular OBU type cannot collide, e.g. there cannot be two different audio elements with ID = 0.
2. IDs across all OBU types cannot collide, e.g. there cannot be an audio element with ID = 0 and a parameter ID = 0.

Maybe this has been answered, but I am confused and wondering if there's a way to make it clearer.

**Comment by tdaede** [comment]
I am pretty sure this means (1), IDs are namespaced by types. Maybe the sentences can say "xxx id indicates an obu uniquely identifiable by obu_id = xxx and obu_type = yyy"

**Comment by tdaede** [comment]
The issue on https://github.com/AOMediaCodec/libiamf/issues/6 interprets it the other way. @sunghee-hwang what was your original intention here?

**Comment by sunghee-hwang** [comment]
@tdaede and @yeroro, it was (1).
