### ISSUE TITLE
Gaps of parameters blocks

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#383]
There is this sentence:
"Between two Sync OBUs, a sequence of audio frames or parameter blocks must be gapless." But even if there is only one Sync OBU (so nothing is between two Sync OBUs), we still want the parameter blocks to cover the whole duration of audio elements that use it (which includes not having audio samples starting earlier/ending later than the parameter).

Maybe change how we talk about the same concept using "covering" instead of "gaps".

**Comment by tdaede** [comment]
Maybe we can just remove the mention of Sync OBUs?

As written, the sentence enforces more than just parameter blocks covering audio frames, it also requires there to not be missing output samples from audio frames.

**Comment by tdaede** [comment]
@jwcullen please add your proposal for rules on parameter block coverage when present.

**Comment by sunghee-hwang** [comment]
It is closed as PR #436 is merged
