### ISSUE TITLE
Clarify Opus Sample Rate

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#384]
The `relative_offset` field in [section 3.12](https://aomediacodec.github.io/iamf/#obu-sync) says

_"The offset shall be indicated in the number of ticks at the sample rate specified in the corresponding substream or Codec Config OBU. For IAMF-OPUS, the sample rate is 48000Hz."_

Subsection [5.1.5](https://www.rfc-editor.org/rfc/rfc7845#section-5.1) in Opus does strongly push towards 48kHz as the output sample rate, but technically does allow other sample rates in some circumstances. I think the intention here is we specify that Opus must be decoded at 48kHz, and it was attempted to be done via the quote above, but the quote above should be better worded to say that Opus MUST be decoded at 48kHz. With that wording it probably belongs in the `IAMF-OPUS Specific` section.

Note this is not to be confused with the `Input Sample Rate` in the same section. This should reflect the actual sample rate of the original encoded signal and not be fixed to any value.

**Comment by tdaede** [comment]
I don't think the section necessarily implied that decode happens at 48kHz, but that all timing values are relative to 48kHz (as is the case in the Ogg Opus and MP4 mappings). We could further restrict it to 48kHz only, given that most applications for IAMF would be running at non-downsampled sample rates. In theory an IAMF implementation running Opus at 24kHz should be equivalent to one running at 48kHz and then downsampling its output to 24kHz.

**Comment by jwcullen** [comment]
The header fields describing the number of samples to trim require some kind of implicit sample rate for calculating the number of samples. Further down/upsampling to a different value from this implicit sample rate should adjust the number of samples to be trimmed.

For IAMF-OPUS should this be understood as based on the Input Sample Rate field within [IAMF-OPUS](https://aomediacodec.github.io/iamf/#iamf-opus-specific) reference to [RFC7845](https://www.rfc-editor.org/rfc/rfc7845#section-5)? Or should it be based on an implied output sample rate?

**Comment by sunghee-hwang** [comment]
@jwcullen and @tdaede 

I feel that some sentences in IAMF spec are written under the assumption that the output sample rate for IAMF-OPUS is 48000Hz (the reason may be that the output of libopus (hybrid mode) is based on 48000Hz.)

I think that IAMF specification 
- needs to say clearly that fields (# of ticks,`num_samples_xxx` etc)  are based on the output sample rate = 48000Hz for IAMF-OPUS.
- needs to follow the codec specifications such as RFC6716 and/or RFC7845 rather than mandating the output sample rate.

**Comment by tdaede** [comment]
To clarify, the Input Sample Rate field is totally independent from this and is purely metadata that should probably either be ignored by the spec entirely, or have a simple sentence like rfc7845: "The input sample rate is treated as metadata which can optionally be used to resample the final output of the IAMF decoder".

For the subsampled decode rates (48/24/16khz) I agree with Sunghee. I think #385 is a bit overly strict, I'll suggest an alternate.
