### ISSUE TITLE
obu_id fields in Sync OBU should be distinguishable among audio_substream_ids and parameter_ids.

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#397]
When the value of audio_substream_id is same as that of parameter_id, it can not be distinguished in Sync OBU.

So, the values of parameter_ids shall be different from the values of audio_substream_ids.

My suggestion is that the value of parameter_id shall be greater than the maximum value of audio_substream_ids in the IA sequence and the minimum value of parameter_id shall be greater than 21.
Also, audio_substream_ids shall be assigned sequentially from 0 to N-1. where N is the total number of substreams of the IA sequence.
NOTE: Since the total number of substreams may change over time, implementers MAY assign parameter_id values ​​greater than 100 to make room for new audio_substream_ids, for example.

**Comment by yeroro** [comment]
I think the `obu_data_type` field can help distinguish the two different cases.

**Comment by sunghee-hwang** [comment]
@yeroro, thank you pointing it out. You are right. So, this is invalid.
