### ISSUE TITLE
Magic Code OBU improvements

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#398]
While reviewing the section about Magic Code OBU, I think a few improvements could be done:
- It is not clear what the purpose of the OBU is used for, why it is necessary. I suggesting adding a note indicating that this magic code OBU is added to permit file type sniffing (https://mimesniff.spec.whatwg.org/)
- It is not clear how Magic Code OBUs shall be treated when packaged in container formats. I suggest adding a note that Magic Code OBU MAY be removed when stored in formats that already provide type identification.
- The definition of the 4CC says "ia_code indicates a ‘four-character code’ (4CC) to identify the start of the IA sequence. It shall be ‘iamf’." The part about starting the sequence is already covered in the Standalone Format definition.
- Add a note that Magic Code OBU shall not be set as redundant. In other words, if a new Magic Code OBU appears in a sequence of OBUs, it starts a new IA Sequence. This could happen when concatenating 2 IA Sequences together.
- The `version` and `profile_version` fields are on 8 bits, while they really on 2 4-bit fields. Consider splitting them. Also, generally speaking it is not clear how to use them, what the consequences on readers. Rephrase semantics with clear shall/should for sequence and for implementations.

**Comment by cconcolato** [comment]
Actually the [standalone format definition](https://aomediacodec.github.io/iamf/#standalone-obu-sequence-order) says:
>An IA sequence is composed of a series of OBUs in the sequence of a set of descriptor OBUs followed by their associated data OBUs, and where this pattern is repeated as many times as needed.

and then:
> A set of Descriptor OBUs shall be placed in the following order regardless of where they appear in the bitstream:
> - One Magic Code OBU
> - All Codec Config OBUs
> - All Audio Element OBUs
> - All Mix Presentation OBUs

This means that a single sequence can have multiple Magic Code OBUs. I suggest rephrasing the standalone format to say:
>An IA sequence is composed of a series of OBUs in the sequence of: one Magic Code OBU, a set of descriptor OBUs (excluding the Magic Code OBU), as indicated in https://aomediacodec.github.io/iamf/#standalone-descriptor-obus, followed by associated data OBUs, as indicated in https://aomediacodec.github.io/iamf/#standalone-data-obus, and where this pattern is repeated as many times as needed.

and to remove "One Magic Code OBU" from https://aomediacodec.github.io/iamf/#standalone-descriptor-obus

**Comment by sunghee-hwang** [comment]
@cconcolato,

Let me share the background why we have made such set of descriptor OBUs.
- A simple case is only one set of Descriptor OBUs. So, in this case we don't need to care about whether the set of descriptor OBUs include Magic Code OBU or not.
Based on this, SG has considered two major issues. One is broadcasting scenario and the other is short-lived contents.
(I will update this soon. Now I need to leave my office)
