### ISSUE TITLE
Codec Config OBU improvements

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#399]
The following comments are about https://aomediacodec.github.io/iamf/#obu-codecconfig

- `codec_id`. 
  - Why prefix all codecs with IAMF? I suggest removing the prefix.
  - for LPCM, is it 'ipcm' or 'lpcm'?
  - Are the other values reserved? Are there values that users can define on their own?
  - The values seem to match the 4CC of `stsd` entries in ISOBMFF. Does it mean that other values can be used?
  - I would suggest using a bullet point list for the possible values of codec ids, or a table.
  - Instead of using "It shall be xxxx for IAMF-XXXX", I suggest rephrasing to say that: 
 > When the value of codec_id is xxxx, the payload of all substreams of all Audio Elements referring to this codec configuration shall comply to the specification XXXX and the decoder_config structure shall comply with the constraints given in section Y

- `num_samples_per_frame`
  - Add a sentence that the value shall match the value in the decoder_config

- roll_distance
"roll_distance is a signed integer that gives the number of frames that need to be decoded in order for a frame to be decoded correctly."
  - What does "decoded correctly" mean? 
  - Clarify that the value shall match the value given in decoder_config, if any.
  - typo: "corrently" -> correctly
  - The use of "R" is unclear. I suggest rephrasing and maybe using a bullet list per codec or the table as suggested above.

**Comment by cconcolato** [comment]
* Thanks for clarifying the `codec_id` and for pointing to 23003-5. FYI, these code points are not yet registered with the MPEG-4 Registration Authority. I raised an issue https://github.com/mp4ra/mp4ra.github.io/issues/167. 
Note that the QuickTime specification also defines `lpcm` see https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap3/qtff3.html#//apple_ref/doc/uid/TP40000939-CH205-BBCGGHJH.

* My comment about decoder_config was regarding `num_samples_per_frame` (not roll_distance)

* Regarding roll distance, some data points:
1. ISOBMFF defines the 2 sample groups that use `roll_distance`:
```
class AudioRollRecoveryEntry() extends AudioSampleGroupEntry ('roll')
{
   signed int(16) roll_distance;
}
class AudioPreRollEntry() extends AudioSampleGroupEntry ('prol')
{
   signed int(16) roll_distance;
}
```
> `roll_distance` is a signed integer that gives the number of samples that need to be decoded in
order for a sample to be decoded correctly. A positive value indicates the number of samples
after the sample that is a group member that need to be decoded such that at the last of these
recovery is complete, i.e. the last sample is correct. A negative value indicates the number of
samples before the sample that is a group member that need to be decoded in order for
recovery to be complete at the marked sample. The value zero shall not be used; those samples
that would be covered by the value zero can be signalled by other signaling mechanisms such as
the sync sample table, the 'rap ' sample grouping and the 'sap ' sample grouping.

2. CMAF mentions
> The AAC codec uses audio frames of a fixed length and a transform which applies over two frames. To
obtain correct audio from a frame, both frames in the transform are needed, and hence the prior
encoded frame and the current encoded frame need to be decoded to output the first frame. This is
sometimes called “priming” and may be signalled using the 'roll' sample group.

3. Opus in ISOBMFF defines
> Opus bitstream requires at least 80 millisecond pre-roll after each random access to get correct output.
Pre-roll is indicated by the roll_distance field in AudioRollRecoveryEntry. AudioPreRollEntry shall not
be used since every Opus sample is a sync sample in Opus bitstream. Note that roll_distance is expressed
in sample units in a term of ISO Base Media File Format, and always takes negative values.
For any track containing Opus bitstreams, at least one Sample Group Description Box and at least one
Sample to Group Box within the Sample Table Box shall be present and these have the grouping_type field
set to 'roll'. If any Opus sample is contained in a track fragment, the Sample to Group Box with the
grouping_type field set to 'roll' shall be present for that track fragment.
For the requirement of AudioRollRecoveryEntry, the compatible_brands field in the File Type Box shall
contain at least one brand which requires support for roll groups.

**Comment by sunghee-hwang** [comment]
@cconcolato, thank you for the information regarding LPCM.
FYI, actually the old version was 'lpcm', and then there had been a request from Apple to change it into 'ipcm'.

Now, we have two options. One is based on QuickTime and the other is based on ISOBMFF.
We may choose any one. But, as our spec has been based on ISOBMFF rather than QuickTime. I think that it is more aligned with our spec to keep 'ipcm'.
