### ISSUE TITLE
Audio Frame OBU improvement suggestions

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#400]
I find the term "Audio Frame OBU" a bit hard to understand:
- It is defined as "the raw coded audio frame for an audio substream." 
- It is represented by different types of OBUs `audio_frame_obu_with_no_id` and `audio_frame_obu`
- The `audio_frame_obu_with_no_id` actually starts with an id `audio_substream_id`
- the term Audio OBU (https://aomediacodec.github.io/iamf/#audio-obu) is too close to Audio Frame OBU

I would suggest:
- removing "raw" from the definition
- adding to the definition that "it is represented by different types of OBUs"
- renaming `audio_frame_obu` to `audio_frame_obu_explicit_id` and `audio_frame_obu_with_no_id` to `audio_frame_obu_implicit_id`
- renaming the top level structure from `audio_open_bitstream_unit` to `ia_ open_bitstream_unit`

**Comment by sunghee-hwang** [comment]
Sounds good to me!
