### ISSUE TITLE
Labels should be localized

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#404]
The human-friendly labels do not indicate the language used and the classes do not permit providing labels in multiple languages. Consider adding a loop with language + label_value.

**Comment by sunghee-hwang** [comment]
@cconcolato,
We have following convention.
```
string syntaxName

string indicates the type of a string which is terminated by null of one byte (i.e. 0x00).

syntaxName is a human readable label whose byte representation consists of two-letter primary language subtags and two-letter region subtags which are connected by hyphen("-"), and followed by bytes representation of [UTF-8_Enc(label)](https://aomediacodec.github.io/iamf/#utf-8_enc-label). Its length in bytes is limited to 128.

Where, two-letter primary language subtags and two-letter region subtags conform to [[BCP47]](https://aomediacodec.github.io/iamf/#biblio-bcp47).
```
Do you think that we need something more to indicate the language?

**Comment by cconcolato** [comment]
I find it quite confusing that the type `string` contains the language code. I would suggest either:
1. renaming the type to `localizedString`
2. just having the type `string` be a string and then duplicate the `label` field into `label_language` and `label`.

Also forcing the use of two-letter region subtags can have unintended consequences. For example, if I have to use a region for English, and I pick `en-US`, should I expect that it would be used in the UK? My suggestion is to leave it to the application to use or not a region code.

I think what is still missing is the ability to have multiple labels: one in English, one in Korean, one in French, ...
