### ISSUE TITLE
Parameter block sample rates may need to be additionally restricted wrt audio rate

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#405]
We may not be able to meet the requirement in 5.1.2:

> Between two Sync OBUs, a sequence of audio frames or parameter blocks must be gapless.

Consider a audio rate of 48khz and a parameter block rate of 44.1kHz. Can they be made gapless?

**Comment by sunghee-hwang** [comment]
Addressed by PR #433

**Comment by sunghee-hwang** [comment]
It is closed as PR #433 is merged.
