### ISSUE TITLE
Define major/minor version restrictions

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#406]
Define the contract with regards to major/minor versions and backwards compatibility.

**Comment by sunghee-hwang** [comment]
It is closed as being invalid.

**Comment by cconcolato** [comment]
I don't think that is completely invalid. Even with the change of major/minor versions to profile/compatible_profile, the spec needs a sentence/paragraph that explains backwards compatibility. It should explain that:
- if a reader recognize the profile declared in the bitstream, 
  - it shall be able to parse all OBUs explicitly listed in that profile. 
  - It can still encounter reserved OBUs that it should skip and it is acceptable to do so.
- This allows future versions of the spec to define new profiles that can be backwards compatible to old profiles

**Comment by sunghee-hwang** [comment]
I think that your comments are able to be addressed via PR #453 which is addressing issue #445 and #425.
