### ISSUE TITLE
Element of `demixing_matrix`  should be of type singed int

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#408]
In the class definition of `ambisonics_projection_config()`, the `demixing_matrix` is defined as follows:
``` 
  unsigned int (16 * (N + M) * C) demixing_matrix;
```

And the following text
> demixing_matrix complies with the one for [ChannelMappingFamily](https://opus-codec.org/docs/opus_in_isobmff.html#) = 3 in [[RFC8486]](https://aomediacodec.github.io/iamf/#biblio-rfc8486) except the byte order of each of matrix coefficients is converted to big endian.

But in  [ChannelMappingFamily](https://opus-codec.org/docs/opus_in_isobmff.html#) = 3 in [[RFC8486]](https://aomediacodec.github.io/iamf/#biblio-rfc8486), we have this text saying the number should be signed:
> The coefficients of the demixing matrix stored in column-major
>  order as 16-bit, **signed**, two's complement fixed-point values with
>  15 fractional bits (Q15)

So I think we should change the line to:
```
  signed int (16 * (N + M) * C) demixing_matrix;
```

**Comment by tdaede** [comment]
This was fixed by https://github.com/AOMediaCodec/iamf/pull/430
