### ISSUE TITLE
Consider the update of recon_gain operation in terms of #415

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#417]
The smoothing operation of recon_gain needs to be done when the recon_gain value are changed.
When we consider #415, the location of smoothing needs to be done at the start of the decoded audio frame rather than the end of the decoded audio frame so that it will not create one frame delay caused by the smoothing operation.

**Comment by tdaede** [comment]
This was fixed by https://github.com/AOMediaCodec/iamf/pull/434
