### ISSUE TITLE
Replace "timeline" with a description of what needs to be checked

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#443]
> - Every Parameter in ths IA sequence shall have the same timeline with that of Substream.

< @cconcolato > Can we replace 'timeline' with the actual bitstream elements that should be checked: relative offset, sample rate and number of samples?

**Comment by cconcolato** [comment]
Maybe it's worth having a "Timing model" section that defines how to compute, generically, the start time and duration of different elements: audio frame, parameter block, temporal unit, sequence, i.e., generally the start time of an audio frame (resp. parameter) OBU is the sum of the relative offset for the substream (resp. parameter stream) and the sum of the duration of all previous OBUs in the same substream (resp. parameter stream); and the duration of an OBU is ... 

Then the profiles section could refer to these terms and indicate that under the restrictions of the profiles, the timing is simplified.
