### ISSUE TITLE
Should we require UTF-8 to not allow NUL character to avoid confusion with nul-termination?

### ISSUE THREAD

**Issue by shawn-singh** [AOMediaCodec/iamf#448]

**Comment by sunghee-hwang** [comment]
Would there be a case which an output of UTF-8 is including NUL character except nul-termination?

**Comment by tdaede** [comment]
UTF-8 does allow null (the zero code point).

**Comment by tdaede** [comment]
Because we use null-termination, nulls in the string are already forbidden. We could add text to make this more explicit.

**Comment by sunghee-hwang** [comment]
> Because we use null-termination, nulls in the string are already forbidden. We could add text to make this more explicit.

What I understand from the sentence is that the output of UTF-8 Enc (label) (i.e. UTF-8 Octet sequence) shall not include 0x00 byte.
Based on the reference (RFC 3629), unicode U+0000 (the number 0) is coded to 0x00 byte by UTF-8 Enc.

Does it mean that human readable label itself shall not contain "0"? For example, 
- "MixPresentation0" is not allowed as human readable label.

**Comment by sunghee-hwang** [comment]
PR #458 is addressing this.
