### ISSUE TITLE
Need to restrict that a sample group of type 'roll' shall presents for codec_id = "Opus" or "mp4a" 

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#465]
Section 10.1.3 of ISOBMFF says that the value zero for roll_distance shall not be used.
Meanwhile, `roll_distance` in `Codec Config OBU` shall be set to 0 when `codec_id` = 'fLaC' or 'ipcm'.

So, the sample group is not required when `codec_id` = 'fLaC' or 'ipcm'.

Also, both ISOBMFF and IAMF use the same syntax name `roll_distance' but its semantics are a bit different each other as described in above.
 it is better to use a difference syntax name in `Codec Config OBU` for roll distance. My suggestion is to use `audio_roll_distance`.

**Comment by tdaede** [comment]
Will be fixed by #466
