### ISSUE TITLE
Clarify if mixed order ambisonics is allowed and how to use it.

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#467]
[3.7.2](https://aomediacodec.github.io/iamf/#syntax-ambisonics-config) has text about `output_channel_count`, `substream_count`, and `channel_mapping`. It references [RF 8486](https://www.rfc-editor.org/rfc/rfc8486#section-3.1) which allows `channel_mapping` to use `255` to represent missing channels.

Is mixed-order ambisonics supposed to be able to be used or not? If not perhaps text should be added to `channel_mapping` to restrict `255` from being used. If it is then maybe `substream_count` should be allowed to be less than or equal to `output_channel_count`. 

Section [8.1](https://aomediacodec.github.io/iamf/#iamfgeneration-ambisonics) seems to prevent this:
_"[output_channel_count](https://aomediacodec.github.io/iamf/#output_channel_count), [substream_count](https://aomediacodec.github.io/iamf/#substream_count) and [coupled_substream_count](https://aomediacodec.github.io/iamf/#coupled_substream_count) shall be set to the number of channels for Ambisonics."_

**Comment by sunghee-hwang** [comment]
@jwcullen,

You are right. substream_count and coupled_substream_count should have been removed.

Let me address it through PR#440.
