### ISSUE TITLE
RFC 2119 text should be updated to include (and the spec should use) RFC 8174

### ISSUE THREAD

**Issue by jzern** [AOMediaCodec/iamf#468]
```
   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
   "OPTIONAL" in this document are to be interpreted as described in
   BCP 14 RFC2119 RFC8174 when, and only when, they appear in all
   capitals, as shown here.
```

8174 clarified the requirements for capitalization. The spec should use all caps MUST, SHOULD, etc. to make the requirements clear.

https://www.rfc-editor.org/info/rfc2119
https://www.rfc-editor.org/info/rfc8174

**Comment by tdaede** [comment]
We need to figure out how to make bikeshed reference rfc8174 rather than rfc2119.

**Comment by tdaede** [comment]
The spec also contains the sentence "However, for readability, these words do not appear in all uppercase letters in this specification. "

This should be removed.

**Comment by tdaede** [comment]
The spec is now using RFC 8174 capitalization. The bikeshed file now needs to be updated to reference it rather than 2119.
