### ISSUE TITLE
Consider removing sub-mix loop

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#490]
We currently only allow one sub-mix. We could remove the loops that define the mix presentation for multiple sub-mixes.

The existing mechanism allows for extensibility by adding multiple sub-mixes later, but the behavior would need to be strictly defined in order for old decoders to be compatible with newer bitstreams.

**Comment by sunghee-hwang** [comment]
We may go to change bitstream by deleting num_sub_mixes field or go to update device's operation which says only the first mix is parsed when num_sub_mixes > 1.

**Comment by sunghee-hwang** [comment]
My suggest is to add a capability in Simple Profile section as follows:
`If a decoder or an OBU parser encounters a Mix Presentation OBU with [=num_sub_mixes=] > 1, it SHALL discard the Mix Presentation OBU.
