### ISSUE TITLE
Consider increasing the space available for reserved OBU IDs

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#492]
- Consider separate namespaces for descriptor and non-descriptor OBUs
- Consider using extension header to include a longer OBU type id
- Consider reducing the number of OBU types for audio streams with IDs

**Comment by jwcullen** [comment]
Consider reducing from OBU_IA_Audio_Frame_ID0 -> OBU_IA_Audio_Frame_ID21 instead to OBU_IA_Audio_Frame_ID0 -> OBU_IA_Audio_Frame_ID17. That allows using 18 channels (max base profile) number of channels without the extra LEB128 overhead.

**Comment by felicialim** [comment]
> Consider separate namespaces for descriptor and non-descriptor OBUs

We'll need > 5 bits to represent all the OBU types, so this would incur a bitrate overhead.

> Consider using extension header to include a longer OBU type id

Could you please elaborate?
