### ISSUE TITLE
Consider removing leb128 in unnecessary locations

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#494]
Bits could be saved by reducing / removing leb128 for cases where there is a low max length.

**Comment by jwcullen** [comment]
The main benefit for this would be to save a byte. A leb128 is identical to a uint8_t when representing 0 - 127. The main use of saving bits would be in Audio Frame OBUs and Parameter Block OBUs.

I don't see any leb128s in those OBUs that I think should be made into uint8_t. They either normally are using a range of values which benefit from being leb128 or are prudent to support many values to avoid conflicts. For many simple cases the "typical" values could fit into 1 byte anyway.

My vote is this is not needed and the spec is fine as is.

**Comment by tdaede** [comment]
Our definition for leb128 places a limit on the size of a decoded leb128 to 32 bits.

**Comment by tdaede** [comment]
We have no more locations to remove leb128, closing.
