### ISSUE TITLE
Split introduction into use case / example and IAMF model

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#497]
The IAMF model should be presented in a high to low level order.

**Comment by cconcolato** [comment]
I would suggest the following structure
1. Introduction, with text from:
Immersive Audio definition
3D Audio Signals definition
range of devices and applications
Use cases

2. Model, with 
- 2.1 Terminology (all the terms defined today)
- 2.2 Architecture
- 2.3 Bitstream structure 
- 2.3.1 IA Sequence
- 2.3.2 Use of OBU
- 2.4 Timing
