### ISSUE TITLE
Deduplicate the text for profile_compatible and profile_name

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#498]
Deduplicate the text for profile_compatible and profile_name:
```
    0: Simple Profile

    1: Base Profile

    2~255: Reserved
```

When a stream complies to only one profile, it currently has to specify the same profile twice. Instead, a special value for profile_compatible could indicate that it is not compatible with any other profiles.

**Comment by jwcullen** [comment]
I think this is labeled wrong. This is just editorial so both fields can use the same enums. They already use the same values in the published version of the spec.

**Comment by tdaede** [comment]
We've decided to signal having no backwards compatible bitstream profile by setting both fields to the same value, and not having a dedicated sentinel value.

We'll leave this issue open until the enums in the spec are deduplicated by #505 .
