### ISSUE TITLE
Specify restriction on leb128 explicitly to be 32 bits max.

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#511]
We could potentially copy the leb128 definition in from the AV1 spec and drop the normative reference, or at least add the limit explicitly to our definition section.

**Comment by jwcullen** [comment]
There was discussion that this was intended as decoding to 64 bits max instead of 32 bits. I am fine with either way, but can someone please clarify what the upper limit was supposed to be? @sunghee-hwang

**Comment by sunghee-hwang** [comment]
Please refer to this.
https://github.com/AOMediaCodec/iamf/issues/512#issuecomment-1610320689
