### ISSUE TITLE
IA Sample format question

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#540]
Can a sample hold an updated [Audio Element OBU](https://aomediacodec.github.io/iamf/#audio-element-obu) or a [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) which is different from the one which is stored in the sample entry?

If yes, do we need additional restrictions and/or signaling which would indicate how this information appears in samples?
One way to signal could be the use of dedicated 4CCs similar how it's done in MPEG to signal in-band vs out-of-band config information. 

If this is not allowed then this issue can be closed and the only request would be to clarify the sample format definition to make it more clear how the sample is defined.

**Comment by cconcolato** [comment]
> Can a sample hold an updated [Audio Element OBU](https://aomediacodec.github.io/iamf/#audio-element-obu) or a [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) which is different from the one which is stored in the sample entry?

I would say: no. Descriptor OBUs SHALL only be in the `configOBUs` in the sample entry and new sample entries need to be defined when they change.

I agree this needs to be clarified.

I would like to avoid having 2 4CCs for the sample entry.

**Comment by sunghee-hwang** [comment]
I copy the current definition of IA Sample below.

For tracks using the [IASampleEntry](https://aomediacodec.github.io/iamf/#iasampleentry), an IA Sample has the following constraints:

- One IA Sample data SHALL be one [Temporal Unit](https://aomediacodec.github.io/iamf/#temporal-unit) and SHALL NOT contain [Temporal Delimiter OBU](https://aomediacodec.github.io/iamf/#temporal-delimiter-obu).

- The decode duration of an IA Sample SHALL equal the duration of the underlying [Temporal Unit](https://aomediacodec.github.io/iamf/#temporal-unit), i.e. the decode duration of the [Audio Frame OBU](https://aomediacodec.github.io/iamf/#audio-frame-obu).
