### ISSUE TITLE
Consider limiting the max size of an OBU (possibly for only currently defined profiles)

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/iamf#542]

**Comment by sunghee-hwang** [comment]
How about 65536B?
When we consider LPCM 192KHz, 24bit, 2ch, its frame duration can be up to 65536/(192000 x 3 x 2) = about 56.8ms.

**Comment by tdaede** [comment]
With leb128 being limited to 32 bits I think this a bit less of an issue as well.
