### ISSUE TITLE
How is loudness for `layout_type = 0` (NOT_DEFINED) used?

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#553]
In [`class layout()`](https://aomediacodec.github.io/iamf/#syntax-layout), the `layout_type` can be 0.

On the encoder side, when will this be generated?
On the decoder side, how is this information expected to be used? Note it's still possible to specify all the loudness info for this undefined layout, but I imagine it's hard to use it to normalize the loudness for example.

If there is no use, maybe we should delete this value.

**Comment by sunghee-hwang** [comment]
@felicialim 
Let me know your opinion on this.

**Comment by felicialim** [comment]
Deleting this value makes sense.
