### ISSUE TITLE
Are thresholds of -80dB and -6dB for computing recon gain mandated or recommended?

### ISSUE THREAD

**Issue by yeroro** [AOMediaCodec/iamf#554]
In the section about [recon gain generation](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-recongaingeneration), two thresholds are mentioned:

> If 10*log10(level Ok / maxL^2) is less than the first threshold value (e.g. **-80dB**), ...

> If 10*log10(level Ok / level Mk ) is less than the second threshold value (e.g. **-6dB**), ...

They are described as examples (e.g.), but I think they should be required. Otherwise the decoder does not know the threshold values because they are not sent in the bitstream.

**Comment by sunghee-hwang** [comment]
@yeroro,
Thanks for reviewing it. 

Let me share the current decoder operation for recon gain.
It just applies the value of a recon gain delivered in the bitstream to the frames of relevant channels.
So, we don't need to let it know the threshold values.

I agree to recommend the threshold values for the encoders.

**Comment by tdaede** [comment]
If this is just a recommended example, we should make it clearer (or maybe use a simpler example)
