### ISSUE TITLE
Need to clarify the meaning of non-redundant OBU in the semantics for an OBU payload identifier.

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#556]
There is an incorrect sentence in semantics for an OBU payload identifier because [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) may have no non-redundant OBUs. 

For example, in the following semantics of codec_config_id,
`codec_config_id` defines an identifier for a codec configuration. Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), there SHALL be exactly one non-redundant [Codec Config OBU](https://aomediacodec.github.io/iamf/#codec-config-obu) with a given identifier. [Audio Element](https://aomediacodec.github.io/iamf/#audio-element)s that need a decoder configuration based on this codec configuration refer to this identifier.

Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), there SHALL be exactly one non-redundant [Codec Config OBU](https://aomediacodec.github.io/iamf/#codec-config-obu) with a given identifier.

should be

Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), there SHALL be exactly one non-redundant [Codec Config OBU](https://aomediacodec.github.io/iamf/#codec-config-obu) with a given identifier. Each OBU in the first Descriptors within the [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) is regarded as a non-redundant OBU regardless of the value of its [obu_reduntant_copy](https://aomediacodec.github.io/iamf/#obu-redundant-copy).

It should also be applied to Audio Element OBU, Mix PResentation OBU, and Audio Frame OBU!

**Comment by felicialim** [comment]
Maybe we shouldn't allow no non-redundant OBUs - the first time an OBU appears in an IA sequence, it must be non-redundant. I can't remember the original reason for allowing no non-redundant OBUs. However, in the future we wish to merge two IA sequences, and the second IA sequence has all redundant OBUs, we will need an extra check to ensure this flag is correctly set the first time the OBUs appear in the new IA sequence.

**Comment by sunghee-hwang** [comment]
I think both has pros and cons.
If we do not allow it, a capturing during a live stream requires to edit the first descriptors to be captured. As a capturing may not start at descriptors, it is a bit not simple.
If we do allow it, two files's concatenating requires to edit the first descriptors of the second IA sequence.

**Comment by sunghee-hwang** [comment]
> Maybe we shouldn't allow no non-redundant OBUs - the first time an OBU appears in an IA sequence, it must be non-redundant. I can't remember the original reason for allowing no non-redundant OBUs. However, in the future we wish to merge two IA sequences, and the second IA sequence has all redundant OBUs, we will need an extra check to ensure this flag is correctly set the first time the OBUs appear in the new IA sequence.

As long as the spec allows redundant copies of Descriptors, an IA Sequence can start at any Descriptors.
In broadcasting scenario, each OBU of the first Descriptors of the IA Sequence what devices receives is not marked as non-redundant in most cases.
