### ISSUE TITLE
Section link for channelgroup in Section 3.6 is out-of-date

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#614]
A [ChannelGroup](https://aomediacodec.github.io/iamf/#channelgroup) is defined in [§ 8 IAMF Generation Process (Informative)](https://aomediacodec.github.io/iamf/#iamfgeneration).

should be

A [ChannelGroup](https://aomediacodec.github.io/iamf/#channelgroup) generation rule is described in [§ Annex B-5: ChannelGroup Generation Rule](https://aomediacodec.github.io/iamf/#iamfgeneration-scalablechannelaudio-channelgroupgenerationrule).

**Comment by tdaede** [comment]
fixed
