### ISSUE TITLE
Relax SHALL constraint on ignoring additional redundant OBUs

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#623]
> If a decoder encounters an OBU with obu_redundant_copy = 1, and it has also received the previous non-redundant OBU, it SHALL ignore the redundant OBU.

Relaxing "SHALL" to "MAY" offers a chance to recover from a corrupted or erroneous OBU previously received. The trade-off is that if the new redundant OBU is in fact wrong, the decoder may end up switching from a correct config to a wrong config.

**Comment by sunghee-hwang** [comment]
Agreed. 
Basically, we don't need to mandate ignoring the redundant OBU, A device may refer to the new one every time.
The flag's meaning is to let devices know that the OBU payload has the same context as the previous one.
We should let the devices choose the previous or the current redundant one.

**Comment by sunghee-hwang** [comment]
When I searched by using "Parsers compliant" or "Parser that", there are 23 sentences that are using the term "SHALL" or "SHOULD". It is ambiguous when SHALL is used or when SHOULD is used.
We may relax all the cases to SHOULD, too.

One example, 

obu_size indicates the size in bytes of the OBU immediately following the obu_size field of the OBU. An OBU MAY have extra bytes after consuming all the bytes per the OBU syntax definition, parsers compliant to this version of the specification SHALL ignore the extra bytes.

should be 

obu_size indicates the size in bytes of the OBU immediately following the obu_size field of the OBU. An OBU MAY have extra bytes after consuming all the bytes per the OBU syntax definition, parsers compliant with this version of the specification SHOULD ignore the extra bytes.
