### ISSUE TITLE
Typo in note about trimming?

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#626]
In the Semantics for `obu_trimming_status_flag`:

"Because of coding dependency, discarding a sample can sometimes mean decoding the entire audio frame."

Should this be about discarding, not decoding the entire audio frame?

**Comment by sunghee-hwang** [comment]
I understand the sentence means discarding a sample is a result of decoding the entire audio frame

**Comment by tdaede** [comment]
The implication here is that discarding samples means you may still need to decode the frame. We can clarify this further on a future version.
