### ISSUE TITLE
Move recommended scalable channel layout selection to 8.2?

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#632]
> For a given input audio with [audio_element_type](https://github.com/AOMediaCodec/iamf/issues/new#audio_element_type) = CHANNEL_BASED, if the input audio has height channels (e.g 7.1.4ch or 5.1.2ch), it is RECOMMENDED to use channel layouts with height channels (i.e., higher than or equal to 3.1.2ch) for all [loudspeaker_layouts](https://github.com/AOMediaCodec/iamf/issues/new#loudspeaker_layout).

Would it make sense to move the paragraph starting with the above from Section 3.6.2 to Section 8.2?

**Comment by felicialim** [comment]
We may want to also consider moving the two NOTES that come after them but I'm less certain where's a better place.

> Contents providers may be satisfied with the [down-mixed audio](https://github.com/AOMediaCodec/iamf/issues/632#down-mixed-audio) having ...

Maybe the rendering section (7.3.2)?

> The Ltr and Rtr of 5.1.4ch down-mixed from 7.1.4ch is within the range of Ltb and Rtb of 7.1.4ch.

Not sure I follow this.

**Comment by felicialim** [comment]
There's a block of text between the 3.6.2/Syntax and 3.6.2/Semantics that we may also want to consider moving (as a whole or in parts) to other section of the spec. WDYT?

> When an [Audio Element](https://aomediacodec.github.io/iamf/#audio-element) is composed of G(r) number of [Audio Substream](https://aomediacodec.github.io/iamf/#audio-substream)s, scalable channel audio for the [Audio Element](https://aomediacodec.github.io/iamf/#audio-element) is layered into [num_layers](https://aomediacodec.github.io/iamf/#num_layers) = r number of [ChannelGroup](https://aomediacodec.github.io/iamf/#channelgroup)s....

**Comment by sunghee-hwang** [comment]
> > For a given input audio with [audio_element_type](https://github.com/AOMediaCodec/iamf/issues/new#audio_element_type) = CHANNEL_BASED, if the input audio has height channels (e.g 7.1.4ch or 5.1.2ch), it is RECOMMENDED to use channel layouts with height channels (i.e., higher than or equal to 3.1.2ch) for all [loudspeaker_layouts](https://github.com/AOMediaCodec/iamf/issues/new#loudspeaker_layout).
> 
> Would it make sense to move the paragraph starting with the above from Section 3.6.2 to Section 8.2?

Logically, it makes sense but section 8.2 is informative.

**Comment by sunghee-hwang** [comment]
> We may want to also consider moving the two NOTES that come after them but I'm less certain where's a better place.
> 
> > Contents providers may be satisfied with the [down-mixed audio](https://github.com/AOMediaCodec/iamf/issues/632#down-mixed-audio) having ...
> 
> Maybe the rendering section (7.3.2)?
> 
> > The Ltr and Rtr of 5.1.4ch down-mixed from 7.1.4ch is within the range of Ltb and Rtb of 7.1.4ch.
> 
> Not sure I follow this.

Please refer to https://github.com/AOMediaCodec/iamf/issues/437

**Comment by tdaede** [comment]
We will leave it where it is.
