### ISSUE TITLE
Clarify whether first descriptors are allowed to be redundant

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#635]
The following sentence suggests that it might be fine to have the first Descriptors marked redundant IF it is the first IA Sequence in the entire bitstream.

> NOTE: In a typical case, the first [Descriptors](https://github.com/AOMediaCodec/iamf/issues/new#descriptors%E2%91%A0) of the [IA Sequence](https://github.com/AOMediaCodec/iamf/issues/new#ia-sequence) are all non-redundant (i.e. [obu_redundant_copy](https://github.com/AOMediaCodec/iamf/issues/new#obu_redundant_copy) = 0).

But there are also other sentences, e.g.

"Within an IA Sequence, there SHALL be exactly one non-redundant Mix Presentation OBU with a given identifier"

which effectively means that the first one SHALL be marked redundant. 

My preference is still for the latter as it creates one less edge case to take care of but we should either:

1. modify the other sentences throughout spec if we want to relax the constraint
2. clarify the NOTE if we want to enforce the constraint

Decoder behaviour is unaffected either way, since it will always treat the first OBU it sees as non-redundant.

**Comment by sunghee-hwang** [comment]
> The following sentence suggests that it might be fine to have the first Descriptors marked redundant IF it is the first IA Sequence in the entire bitstream.
> 
> > NOTE: In a typical case, the first [Descriptors](https://github.com/AOMediaCodec/iamf/issues/new#descriptors%E2%91%A0) of the [IA Sequence](https://github.com/AOMediaCodec/iamf/issues/new#ia-sequence) are all non-redundant (i.e. [obu_redundant_copy](https://github.com/AOMediaCodec/iamf/issues/new#obu_redundant_copy) = 0).
> 
> But there are also other sentences, e.g.
> 
> "Within an IA Sequence, there SHALL be exactly one non-redundant Mix Presentation OBU with a given identifier"
> 
> which effectively means that the first one SHALL be marked redundant.
> 
> My preference is still for the latter as it creates one less edge case to take care of but we should either:
> 
> 1. modify the other sentences throughout spec if we want to relax the constraint
> 2. clarify the NOTE if we want to enforce the constraint
> 
> Decoder behaviour is unaffected either way, since it will always treat the first OBU it sees as non-redundant.

Anyway, the original intention was to say that there shall be one unique identifier per Mix Presentation and that there shall be a unique in one set of Descriptors. I don't think that there would be a reason to deliver two Mix Presentation OBUs storing the same Mix Presentation in one set of Descriptors. But, I am fine to clarify it too.

How about rephrasing the semantics as follows:

mix_presentation_id defines an identifier for a [Mix Presentation](https://aomediacodec.github.io/iamf/#mix-presentation). Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), there SHALL be exactly one non-redundant [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) with a given identifier. Each [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) in the first [Descriptors](https://aomediacodec.github.io/iamf/#descriptors%E2%91%A0) within the [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) is regarded as a non-redundant OBU regardless of the value of its [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy). This identifier MAY be used by the application to select which [Mix Presentation](https://aomediacodec.github.io/iamf/#mix-presentation)(s) to offer.

should be

mix_presentation_id defines an identifier for a [Mix Presentation](https://aomediacodec.github.io/iamf/#mix-presentation). Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), there SHALL be one unique [mix_presentation_id](https://aomediacodec.github.io/iamf/#mix_presentation_id) per [Mix Presentation](https://aomediacodec.github.io/iamf/#mix-presentation). There SHALL be exactly one [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) with a given [mix_presentation_id](https://aomediacodec.github.io/iamf/#mix_presentation_id) in a set of Descriptors. This identifier MAY be used by the application to select which [Mix Presentation](https://aomediacodec.github.io/iamf/#mix-presentation)(s) to offer.

And 

Each [Mix Presentation OBU](https://aomediacodec.github.io/iamf/#mix-presentation-obu) in the first [Descriptors](https://aomediacodec.github.io/iamf/#descriptors%E2%91%A0) within the [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) is regarded as a non-redundant OBU regardless of the value of its [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy).

should move to Section 5.1 with a modification as follows:

Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), each OBU in the first [Descriptors](https://aomediacodec.github.io/iamf/#descriptors%E2%91%A0) SHALL be regarded as a non-redundant OBU regardless of the value of its [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy).
