### ISSUE TITLE
Labels 

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#653]
Hi guys,

we are currently reviewing the spec. Can I ask you to create the following labels so I can open issues here to track some of the suggestions we found?

I think that it will make sense to create labels for the following review comments:

- editorial comment
- technical comment
- general comment

also it seems that I can not assign labels to issues myself but I would like to run a script to open all issues I found so far. It would be more efficient if I label them correctly while opening instead of doing it afterwards.

**Comment by tdaede** [comment]
We have "editorial", "bug", and "question" labels that I think approximately correspond to those categories.

I have to add a permission to be able to set labels and assignees. I've added it for you, let me know if it needs to be added to anyone else as well.

**Comment by podborski** [comment]
Hi Thomas @tdaede it seems that I still do not have permissions to add labels to issues. Can you check?

Good that we have editorial one. For other labels I think it still makes sense to add those as it is to the group to decide if something is a bug or not. And question does not apply in some cases. 

I'll follow a similar processes as we use in national body comments in ISO. Gathering comments in a doc and then we can dump all the entries from that doc as separate issues to the GitHub repo. (thinking to propose it to entire AOM actually, as I believe this would be good for every spec the group is developing, but this is a separate discussion)

**Comment by podborski** [comment]
thanks
