### ISSUE TITLE
On SDL Syntax

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#654]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|all|

#### Comment:
Section 9 claims to use the valid SDL syntax, but the current version does not define a valid SDL syntax. (This is also sometimes an issue within MPEG itself but if possible, we should not propagate errors).

Here are few examples of what I mean.

```
class ia_open_bitstream_unit() {
    obu_header();
...
}
```
is not a valid SDL syntax because it does not specify an element of the type obu_header. The valid syntax would look something like `OBUHeader obu_header;`

Another recommendation would be to define the class names in CamelCase and the elements in snake_case, like suggested above. This would allow better differentiation between types and elements themselves. 

Note that in clause 3.6 you mix both types of the syntax. For example you define correclty `ReconGainParamDefinition recon_gain_info;`
and you also follow the CamelCase vs snake_case suggestion. It would be good to stick to the same flavour.

-----
#### Suggestion:
Improve SDL syntax.

**Comment by felicialim** [comment]
PR #699 is a first pass. If the changes make sense, I'll go ahead with the other sections in the same style.
