### ISSUE TITLE
§3.2: On OBU trimming

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#657]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§3.2|

#### Comment:
<blockquote>
obu_trimming_status_flag indicates whether this OBU has audio samples to be trimmed. It SHALL be set only when obu_type is set to OBU_IA_Audio_Frame or OBU_IA_Audio_Frame_ID0 to OBU_IA_Audio_Frame_ID17.
</blockquote>

Perhaps it would be better to say it SHALL be set to zero or one if the `obu_type` is set to X, Y or Z, otherwise it shall be set to 0. Just to make sure that you don’t mean it shall be set to 1 for these types.

-----
#### Suggestion:
Clarify if trimming is optional

**Comment by sunghee-hwang** [comment]
"Setting a flag means setting the value to 1."
If this is common sense then I think we should follow the suggestion by @podborski, because it is not necessarily required to set the flag for all Audio Frame OBUs.
