### ISSUE TITLE
§3.2: On coding dependency NOTE

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#658]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§3.2|

#### Comment:
<blockquote>
NOTE: Because of coding dependency, discarding a sample can sometimes mean decoding the entire audio frame.
</blockquote>

Should it be, "Because of possible coding dependencies ... " ?

**Comment by cconcolato** [comment]
Given that it's a NOTE and that the rest of the NOTE already contains "sometimes", adding "possible"  wouldn't hurt bit is not necessary. I would suggest closing this issue without action.
