### ISSUE TITLE
§1: Immersive audio and 3D audio signal terms

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#662]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§1|

#### Comment:
Clause 1 defines 2 terms. `Immersive Audio` and `3D audio signal`. Terminology is defined in clause 2.1. These terms should be moved there.

Also the order of the terms should be changed because 3D audio signal is used in the definition of the Immersive Audio. Or if alphabetical order is used it will also be the other way around.

-----
#### Suggestion:
Change the order and consider moving the terms to section 2.1.
Make sure that the same sorting principle applies across the spec.

**Comment by felicialim** [comment]
We also use other terms (e.g., `Audio Element`) in Section 1 before defining them, so in #705 I've moved `Immersive Audio` and `3D audio signal` down to Section 2.1 following @podborski's suggestion, and relied on hyperlinks to address that issue.

But we also have other terms that could be argued to be missing from there (e.g. IA Sequence) so I've also merged with the Terminology section with the Model Overview section, as suggested by @cconcolato.
