### ISSUE TITLE
§1: Typo

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#663]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§1|

#### Comment:
<blockquote>
IAMF is used to provide Immersive Audio content ...
</blockquote>

-----
#### Suggestion:
F in IAMF stands for Formats (plural) but the text is saying "is used". Maybe better to spell out “Immersive audio model is used … “?

**Comment by cconcolato** [comment]
I think IAMF here refers to the specification. I would close the issue without action or change IAMF to "This specification" in this sentence.

**Comment by tdaede** [comment]
Consensus is to close without change.
