### ISSUE TITLE
Improve figures

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#665]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|all|

#### Comment:
All figures should follow the same styling (e.g. same font, same colours, etc.)

Figure 1: Contrast issues, text in green blocks too dark or the colour of the boxes too dark. Increase contrast. Caption does not mention that this is an example
Figure 2: Text size is too small. Codec Enc. Codec Dec. almost invisible because of contrast issues. (Terms Codec Enc. / Dec. should also be improved (see related issue))

Figure 3: Small text, contrast, styling
Figure 4: contrast issues, formula symbols
Figure 5: resolution issues,
Figure 6: should be a table
Figure 7: Contrast issues, text hard to read
Figure 8: Gray background in the text, not using same styling
Figure 9: Text placement can be improved
Figure 10: Text placement can be improved. Also text too large (make sure to keep same font size across figures whenever possible)
Figure 11: same
Figure 13 - 16:  should be rather formulas (is it possible to use MathML?)
Figure 17: Use same styles, gray background in some of the text
Figure 18: Text placement
Figure 19: text too small
Figure 20: text too small, resolution issues
Figure 21: same
Figure 22: Enc. vs Encs. does not look good in the specification. Please fix.
Figure 23: could be a formula as well. MathML?

-----
#### Suggestion:
Improve all figures across the spec.

**Comment by cconcolato** [comment]
IMHO, this is a nice to have. Whatever can be done before publication should be done, the rest can be deferred to the next version.

**Comment by sunghee-hwang** [comment]
Is there any guideline for figures (resolution, font size, color, style, etc..) in Bikeshed or HTML?

**Comment by cconcolato** [comment]
Not that I know of, but I think we should prefer vector graphics.
