### ISSUE TITLE
§2.2: Generic file packager

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#669]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§2.2|

#### Comment:
<blockquote>
- A File Packager (ISOBMFF Encapsulation) generates an IAMF File by encapsulating the IA Sequence into [ISOBMFF] track(s).
</blockquote>

<blockquote>
- A File Parser (ISOBMFF Parser) reconstructs the IA Sequence by decapsulating the IAMF File.
</blockquote>

Don’t you want to define it more generic here? OBU stream packager? Somewhere later in the specification you can mention that in the current version you only define the ISOBMFF packaging in clause XYZ. etc.

-----
#### Suggestion:
Consider generalizing the architecture for future extensibility.

**Comment by cconcolato** [comment]
We could simply modify the picture to bypass the ISOBMFF packaging, i.e. go from the "OBU Packetizer" output to "OBU Parser" input, to cover cases where ISOBMFF is not used. I'm not sure the sentences need change, or maybe add "optionally" for those 2 processes.
