### ISSUE TITLE
§2.3: IA Sequence definition

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#672]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§2.3|

#### Comment:
This clause could be improved. When does the IA Sequence start and when does it end? Maybe it would be better to say that it is a sequence of immersive audio OBUs starting with the sequence header OBU etc.

-----
#### Suggestion:
Improve the definition of the IA Sequence as it is a very important construct in the specification. Current definition requires you to dig into multiple clauses to understand what it is.

**Comment by cconcolato** [comment]
As indicated in #671, I think we should consider Section 2 as an overview (it does not contain SHALLs, or SHOULDs), maybe rename it, and point to the formal, normative definitions be in Section 5.
The text currently says:
> An IA Sequence is composed of a series of OBUs in the sequence of a set of [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) followed by their associated [IA Data](https://aomediacodec.github.io/iamf/#ia-data).

with 5.1.1 saying:
> A set of [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) SHALL be placed in the following order regardless of where they appear in the bitstream:

and 5.1.2 saying:
> [IA Data](https://aomediacodec.github.io/iamf/#ia-data) consists of a sequence of [Audio Frame OBU](https://aomediacodec.github.io/iamf/#audio-frame-obu)s, [Parameter Block OBU](https://aomediacodec.github.io/iamf/#parameter-block-obu)s and [Temporal Delimiter OBU](https://aomediacodec.github.io/iamf/#temporal-delimiter-obu)s (if present), according to the rules below:

I find this clear and co-located. I'm all for improving the spec but what is the concrete suggestion here?
