### ISSUE TITLE
OBUs vs Immersive Audio OBUs

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#673]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|all|

#### Comment:
Throughout the spec the term `Open Bitstream Units (OBU)s` is used (e.g. 2.3.1) or just `OBU` (as in clause 3) while in clause 3.1 we define an `Immersive Audio OBU`. We should be using the term we define consistently in the specification.

-----
#### Suggestion:
Use clearly defined terms.

**Comment by cconcolato** [comment]
The SDL syntax calls it IA OBU, but I find it heavy to use IA OBU all the time. I would suggest saying the first time OBU is used that it can be interchangeably called IA OBU.
