### ISSUE TITLE
§2.3.2.1: On IA Sequence Header OBU

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#675]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§2.3.2.1|

#### Comment:
<blockquote>
- IA Sequence Header OBU indicates the start of a full IA Sequence description and contains information related to profiles.
</blockquote>

Indicates the start of the new IA Sequence. Not only a start of IA sequence description. Or is my understanding wrong? Or will the new SH OBU which differs from the previous one start a new sequence? This is not clear when reading this part of specification.

UPDATE: after reading the text below I understand that the redundant flag is used to mark the start of the new sequence. It would be good to mention it here to make clear when a sequence starts / ends.

-----
#### Suggestion:
Clarify when the sequence starts / ends because the pure existence of the SH OBU does not necessarily mean a start of the new sequence.

**Comment by cconcolato** [comment]
As I understand it, the intent is for a sequence to start with the first sequence header (redundant or not) and to end with the first non-redundant SH. 

I think there might be some inconsistency between:
https://aomediacodec.github.io/iamf/#standalone-ia-sequence
> The [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) MAY additionally be repeated redundantly and as frequently as necessary. In this case, the [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy) field in their OBU headers SHALL be set to 1. Within an [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence), each OBU in the first [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) SHALL be regarded as a non-redundant OBU regardless of the value of its [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy).

and
https://aomediacodec.github.io/iamf/#obu_redundant_copy
> If a decoder encounters an OBU with [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy) = 1, and it has also received the previous non-redundant OBU, it MAY ignore the redundant OBU. If the decoder has not received the previous non-redundant OBU, it SHALL treat the redundant copy as a non-redundant OBU and process the OBU accordingly.

and
https://aomediacodec.github.io/iamf/#obu-iasequenceheader
> This OBU MAY be placed frequently within one single [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) for an application such as broadcasting or multicasting. In that case, all [IA Sequence Header OBU](https://aomediacodec.github.io/iamf/#ia-sequence-header-obu)s except the first one SHALL be marked as redundant (i.e., [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy) = 1).

and on the other hand:
https://aomediacodec.github.io/iamf/#standalone-iamf-configuration-changes
> Each OBU in the first set of [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) of the new [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) SHALL be marked as non-redundant (i.e., [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy) = 0 in the OBU header).

The SHALL here seems too strict.

Maybe we could have a single place to provide requirements on redundancy and point to it.

**Comment by sunghee-hwang** [comment]
>Each OBU in the first set of [Descriptors](https://aomediacodec.github.io/iamf/#descriptors) of the new [IA Sequence](https://aomediacodec.github.io/iamf/#ia-sequence) SHALL be marked as non-redundant (i.e., [obu_redundant_copy](https://aomediacodec.github.io/iamf/#obu_redundant_copy) = 0 in the OBU header).

In this sentence, the new IA sequence means the next IA Sequence which has a different configuration from the first IA Sequence. 
So, each OBU of the first set of Descriptors of the new IA Sequence SHALL be marked as non-redundant to be distinguished from the previous IA Sequence.
