### ISSUE TITLE
§2.3.2.1: Improve text

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#676]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§2.3.2.1|

#### Comment:
<blockquote>
- ElementName provides information to {set-up, combine, render} ... 
</blockquote>

Would it be better to write something like "Provides information about ..." or "provides information which is required for ..." or something similar?

**Comment by cconcolato** [comment]
I don't see a problem with the current wording (besides missing articles at the beginning of bullet points, #666)

**Comment by felicialim** [comment]
Fixed by #731
