### ISSUE TITLE
§2.4: On Temporal Units

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#677]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§2.4|

#### Comment:
<blockquote>
The term Temporal Unit means a set of all Audio Frame OBUs with the same decode start time and the same duration from all coded Audio Substreams and all non-redundant Parameter Block OBUs with the decode start time within the duration.
</blockquote>

Do you want to mention Temporal Delimiters here as well?

**Comment by cconcolato** [comment]
I understand your comment, but I think we should be clearer that this is a "logical" (from a temporal point of view) definition of a Temporal Unit. The definition in terms of physical structure (i.e. with a delimiter is provided at https://aomediacodec.github.io/iamf/#iadata).
