### ISSUE TITLE
On formulas

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#683]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|all|

#### Comment:
Formulas should be improved.

-----
#### Suggestion:
Consider using MathML

**Comment by cconcolato** [comment]
IMHO, this is a nice to have. If possible, we can do it for v1, and if not, we defer to v2.

**Comment by podborski** [comment]
Consider using this approach: https://github.com/podborski/AOM-spec-review/wiki/Formulas-in-bikeshed

**Comment by tdaede** [comment]
PR #719 fixes this for figures. We could potentially also fix this for inline text.
