### ISSUE TITLE
§7.6.2: Mathematical operations

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#684]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§7.6.2|

#### Comment:
Mathematical operation `X` is not defined. `*` is defined. But `X` is used in some of the Formulas.
Also consider using MathML instead of figures.

-----
#### Suggestion:
Only use defined operators. Use MathML for formulas.

**Comment by podborski** [comment]
Instead of MathML you can also consider this: https://github.com/podborski/AOM-spec-review/wiki/Formulas-in-bikeshed

**Comment by felicialim** [comment]
@podborski I only found remaining uses of `X` in the figures, or did I miss any in the text as well?

**Comment by podborski** [comment]
@felicialim I believe I only spotted the occurrences in the figures.
