### ISSUE TITLE
§9: Move section 9

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#685]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§9|

#### Comment:
Convention is now at the end of the spec while it would be better to have it in the beginning.

-----
#### Suggestion:
Move this section to the beginning. Be consistent with AV1.
Also name in Conventions.

**Comment by cconcolato** [comment]
I actually made the comments earlier in the development of the specification to have it at the end. Most readers of the spec don't need to read the conventions first, and if they need to, they can follow the table of contents. Also, If the terms are properly linked to the convention section the first time they are used, then the reader can simply follow the link.

**Comment by tdaede** [comment]
No strong preferences here. It can be moved with the same PR that moves informative/normative sections if desired.

**Comment by sunghee-hwang** [comment]
It is closed as PR #747 for section reordering has been merged.
