### ISSUE TITLE
§9.1: What is "it"?

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#686]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§9.1|

#### Comment:
<blockquote>
All syntax elements conform to the Syntactic Description Language specified in [MP4-Systems] unless it is explicitly described in the specification.
</blockquote>

It is not clear what `it` refers to.

**Comment by cconcolato** [comment]
I think we should remove the last part of the sentence and be compliant with SDL but not half-compliant without being explicit about what is not compliant.
