### ISSUE TITLE
§9: No logical operators defined

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#688]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§9|

#### Comment:
We see a table of arithmetic operators but no for logical operators.

**Comment by cconcolato** [comment]
Do we really need to defined the arithmetic operators? Doesn't this come from the SDL specification?

**Comment by felicialim** [comment]
We followed AV1 in defining these (https://aomedia.org/av1/specification/conventions/#arithmetic-operators) but perhaps we can drop the basic operators (addition, subtraction, multiplication and division)
