### ISSUE TITLE
§9.3.2: MOD definition

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#690]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§9.3.2|

#### Comment:
Why is `MOD` defined in upper case?

-----
#### Suggestion:
Is it used in the spec? If not remove it.

**Comment by sunghee-hwang** [comment]
It needs to be closed as it has been already addressed by PR #720.
