### ISSUE TITLE
§References: Issues with the references

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#691]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§References|

#### Comment:
Best Practice is mentioned in a lot of normative references. We are referencing specification. Right? Why is that called Best Practices?

OPUS points to an incomplete spec. Be careful.

Is it possible to avoid referencing Wikipedia?

-----
#### Suggestion:
Improve references

**Comment by podborski** [comment]
[AV1-Convention]
[Conventions](https://aomedia.org/av1/specification/conventions/). Spec. URL: https://aomedia.org/av1/specification/conventions/

is not a valid reference. It need to point to the approved version of the AV1 spec and the section which you want to reference.

**Comment by podborski** [comment]
Better to use this one https://aomediacodec.github.io/av1-spec/av1-spec.pdf

**Comment by cconcolato** [comment]
@andrey-norkin @agrange for visibility on issues referencing the AV1 video specification.

**Comment by tdaede** [comment]
I will provide a link to the 1.0 Opus-in-ISOBMFF mapping.

**Comment by sunghee-hwang** [comment]
If PR #721 is merged, then the spec text is no more referencing Opus-in-ISOBMFF.
It was only referencing ChannelMappingFamily in Opus-in-ISOBMFF. But it could be replaced by ChannelMappingFamily in RFC8486.
