### ISSUE TITLE
§6.2.3: Single codec config OBU

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#694]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§6.2.3|

#### Comment:
Just for my understanding a single codec config OBU is put in the sample entry? This would mean that the same decoder config info is used to initialize all Audio Substreams?

**Comment by cconcolato** [comment]
Yes, the restrictions for the carriage in ISOBMFF as of today is limited to single codec.

**Comment by podborski** [comment]
Single codec using exactly the same decoder init information. That part was a little confusing to me.

**Comment by tdaede** [comment]
All codecs use the same initialization section.
