### ISSUE TITLE
§6.2.3: Improving hyperlinks

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#695]
|Version|Source|Clause(s)|
|:---:|:---:|:---:|
|AOM Working Group Draft, 17 July 2023|Apple|§6.2.3|

#### Comment:
When I click hyperlinks in configOBUs semantics, for example the `Codec Config OBU``,` the hyperlink points to clause 2.3.2.1 while it would be much better (in my opinion) if it would point directly to clause 3.5 where that element is specified.

Also in clause 3.5 I feel like instead of just writing:
<blockquote>
This section specifies the OBU payload of OBU_IA_Codec_Config.
</blockquote>

it could provide a better description based on the text in clause 2.3.2.1. For example this could be written like:
<blockquote>
The Codec Config OBU provides information on how to set up a decoder for a coded Audio Substream. This clause specifies the payload format of the Codec Config OBU.
</blockquote>

Same comment applies to other elements.

**Comment by cconcolato** [comment]
Other examples of hyperlinks pointing to a suboptimal place:
- It is hard to go from [scalable_channel_layout_config ](https://aomediacodec.github.io/iamf/#scalable_channel_layout_config) to https://aomediacodec.github.io/iamf/#syntax-scalable-channel-layout-config
- same for https://aomediacodec.github.io/iamf/#ambisonics_config and https://aomediacodec.github.io/iamf/#syntax-ambisonics-config

**Comment by tdaede** [comment]
@felicialim is working on a PR to fix these links.
