### ISSUE TITLE
No reference to the reference software?

### ISSUE THREAD

**Issue by Frank-Ba** [AOMediaCodec/iamf#729]
The reference software is part of the Deliverable but it doesn't seem to be mentioned in the document. There is also no explanation what the reference software is supposed to contribute or how the tests can be executed if that would be useful.

**Comment by tdaede** [comment]
The AV1 spec provides a link to the reference software. We should use the same mechanism to link to our reference software repository.

**Comment by sunghee-hwang** [comment]
@tdaede, do you know how we can add the paragraph including the link to the ref. s/w like AV1 in the IAMF working draft?
I think that it will probably be added to the same location as AV1 (before Copyright and Licensing Information).
But, I do not get how Copyright and Licensing Information has been added to the IAMF working draft.

**Comment by tdaede** [comment]
Here's the source for the block that generates that section in the av1 spec: https://raw.githubusercontent.com/AOMediaCodec/av1-spec/master/00.cover-legend.md

**Comment by sunghee-hwang** [comment]
I know this. But, AV1 has been using a different tool from IAMF.
We need to figure out how to call it in the bikeshed tool and how to make it to be placed in the right place of IAMF spec.
