### ISSUE TITLE
Adding Frank and Alexis as collaborators

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/iamf#730]
Sent it yesterday through an email to Thomas  but not sure if that was a correct email address or not.

@tdaede could you add Alexis (@alexismt73) and Frank (@Frank-Ba) as collaborators to the https://github.com/AOMediaCodec/iamf and https://github.com/AOMediaCodec/libiamf

**Comment by tdaede** [comment]
Added as collaborators.
