### ISSUE TITLE
Proposed reordering of sections

### ISSUE THREAD

**Issue by Frank-Ba** [AOMediaCodec/iamf#736]
<img width="469" alt="Screenshot 2023-08-25 at 8 59 12 PM" src="https://github.com/AOMediaCodec/iamf/assets/46942654/4d52ce7c-5873-4cc3-bea9-c92901024596">

Move all encoder-side parts into Annexes
The main part should consist mainly of normative bitstream and decoder-side items.

This should be done when most PRs have been merged to avoid merge conflicts.

**Comment by tdaede** [comment]
@sunghee-hwang will create the reordering pull request.

**Comment by sunghee-hwang** [comment]
@Frank-Ba, how about putting the channel layout generation rule into section 3.6.2?
Actually, the loudspeaker_layouts SHALL comply with the rule.
As a result, B3 and B6 are moved to section 3.6.2.1 Channel Layout Generation Rule and section 3.6.2.2 Channel Group Format under section 3.6.2.

**Comment by Frank-Ba** [comment]
> @Frank-Ba, how about putting the channel layout generation rule into section 3.6.2?
> Actually, the loudspeaker_layouts SHALL comply with the rule.
> As a result, B3 and B6 are moved to section 3.6.2.1 Channel Layout Generation Rule and section 3.6.2.2 Channel Group > Format under section 3.6.2.

Yes, I think that makes sense.
