### ISSUE TITLE
The output "Downmix" of Mixer module in Figure 2 should be replaced by "Rendered Mix Presentation"

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#741]
https://github.com/AOMediaCodec/libiamf/issues/58

@Frank-Ba, the output of "Mixer" in Figure 2 should be "Rendered Mix Presentation".
FYI, "Downmix" is a part of the rendering process in the IAMF spec.
So, the output "Downmix" of the Mixer module in Figure 2 needs to be changed to "Rendered Mix Presentation".

**Comment by Frank-Ba** [comment]
There is now a PR for this change.

**Comment by sunghee-hwang** [comment]
It needs to be closed when PR #742 is merged.

**Comment by sunghee-hwang** [comment]
It is closed as the PR #742 has been merged.
