### ISSUE TITLE
Define Xi.Yi.Zi before in each of the sections they are used

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#744]
See https://github.com/AOMediaCodec/iamf/pull/740#issuecomment-1697861607

**Comment by sunghee-hwang** [comment]
> See [#740 (comment)](https://github.com/AOMediaCodec/iamf/pull/740#issuecomment-1697861607)

https://github.com/AOMediaCodec/iamf/pull/740#issuecomment-1698377645
