### ISSUE TITLE
MixPresentationOBU syntax/semantics simplification

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#760]
In the context of #759, I found it hard to navigate the spec around Mix Presentation OBU parameter definitions (element and output gains). IMHO, it could be simplified without changing the semantics or bitstreams, as follows:

The Mix Presentation OBU uses:
```
ElementMixConfig element_mix_config;
```
but `ElementMixConfig` is simply
```
class ElementMixConfig() {
  MixGainParamDefinition mix_gain;
}
```
My suggestion would be to remove the use of `ElementMixConfig` and simply use the following in the MixPresentationOBU
```
 MixGainParamDefinition element_mix_gain;
```
It means also moving the semantics of `mix_gain` from section 3.7.4 to section 3.7, merging it with the semantics of `element_mix_config`

Same for output_mix_config. The syntax in MixPresentationOBU should simply have:
```
MixGainParamDefinition output_mix_gain;
```
instead of 
```
OutputMixConfig output_mix_config;
```
Section 3.7.5 can then be removed and merged with the semantics of output_mix_config (which would become `output_mix_gain`).

**Comment by cconcolato** [comment]
Similarly, the annotation syntax description could be simplified, instead of defining a class with a single field:
```
class MixPresentationElementAnnotations() {
  string audio_element_friendly_label;
}
```
or 
```
class MixPresentationAnnotations() {
  string mix_presentation_friendly_label;
}
```

The MixPresentationOBU could simply contain:
```
  for (i = 0; i < count_label; i++) {
    string presentation_annotations;
  }
```
and 
```
      for (i = 0; i < count_label; i++) {
        string element_annotations;
      }
```

In this case, I think also the use of arrays would simplify further the syntax.
```
string language_labels[count_label];
string localized_presentation_annotations[count_label];
...
string localized_element_annotations[count_label];
```

**Comment by tdaede** [comment]
We should look if we expect these to be updated right away in the version 2. If so we can leave them as is, if not we can simplify them.

**Comment by sunghee-hwang** [comment]
@felicialim, I am going to address this issue in the v1.1 spec. Please let me know if you have a concern.
