### ISSUE TITLE
Channel clarifications

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#764]
The term 'channel' is never defined, but heavily used.

'Channel Group' is defined as a set of audio substreams. One could assume then that a channel is a substream? It would be wrong as for example, the definition coupled_substream_count talks about 'coupled stereo channels'. 

Because the audio_element_type values are `CHANNEL_BASED` and `SCENE_BASED`, one could assume that the term channel only applies to loudspeaker-based channels. This would also be wrong because for example the definition of ambisonics configuration talks about channels and profile restrictions on channel counts mixes ambisonics and others. 

So, the term channel seems overloaded, but I don't think we can change that. I would suggest defining it as:
> a component of a loudspeaker-based representation or a component of an Ambisonics representation.
> When used in the context of "channel group" or in the context of an audio element type (CHANNEL_BASED), it refers to loudspeaker-based channels. 

I would suggest updating Figure 2 to have 2 arrows between "Pre-Processor" and "Codec Encoder (and same between "Codec Decoder" and "Element Reconstructor": one arrow for Channel Groups, one arrow for Ambisonics Channels.

**Comment by sunghee-hwang** [comment]
Thank you for a good suggestion.
The second sentence may not be needed because the components for an Ambiosonics representation are also described as one "channel group" in our specification.

**Comment by MasterInQuestion** [comment]
I wonder a question:
    How should all those sophisticated design be actually presented: when most devices have only Mono/Stereo speakers?..
