### ISSUE TITLE
Duplicate values of audio_element_ids in the same loop should be prohibited

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#766]
The profile restrictions say:
- in the common section:
> [num_audio_elements](https://aomediacodec.github.io/iamf/#num_audio_elements) SHOULD be set to 1 or 2

- in the simple profile section, the bitstream part:
> There SHALL be only one unique [Audio Element OBU](https://aomediacodec.github.io/iamf/#audio-element-obu).

- in the simple profile section, parser part:
> They SHALL be able to reconstruct one [Audio Element](https://aomediacodec.github.io/iamf/#audio-element).

The base profile section says:
> - They SHALL be able to reconstruct two [Audio Element](https://aomediacodec.github.io/iamf/#audio-element)s.
> - They SHALL be able to mix two [Audio Element](https://aomediacodec.github.io/iamf/#audio-element)s.

It talks about the "mix", which is missing in the first simple profile.
So I wonder if one could create a simple profile sequence with 1 audio element but with a submix that has num_audio_elements = 2, repeating the same value, which would not make sense.

I think the spec should say in the `num_audio_elements` semantics that a given value of `audio_element_id` shall not be repeated.

**Comment by jwcullen** [comment]
Agree. For consistent wording throughout the spec I see a similar to the restriction for `anchor_element`:
> There SHALL be no duplicate values of [anchor_element](https://aomediacodec.github.io/iamf/#anchor_element) within one [LoudnessInfo()](https://aomediacodec.github.io/iamf/#loudnessinfo).

We could limit the duplicate values of `audio_element_id` in one Mix Presentation OBU - or maybe per submix?
