### ISSUE TITLE
Language tagging

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/iamf#767]
One use case of IAMF could be having a Music and Effects Audio Element and 2 Dialogue Elements, in 2 different languages, e.g. French and English. It is not very clear how it would be achieved today.

There are several alternatives:
1. One could have 1 Mix Presentation with 2 sub-mixes: a French sub-mix and an English sub-mix. Both sub-mix would refer to the M&E element but then they would use a different Dialogue Element. In that case, there is no annotation at the sub-mix level to provide a User-friendly label, nor to provide language tagging for automatic selection.
2. One could have 2 Mix Presentations. Each would have 1 sub-mix. The sub-mix would include the M&E element and a different Audio element. The presentation-level annotation could provide a user-friendly text to show in the UI. But it's different from providing machine-processable language tagging.  

This was raised in https://github.com/AOMediaCodec/iamf/issues/290. Unfortunately, the annotation structure is not extensible (and currently says "friendly" meaning "user visible"). Maybe we could define a structure for the string, for example say that ":" is a separator and that the string shall be formed like `<language_code>:[<role>:]*<user-targeted-label>`.

Alternatively we could use the "parameter" concept at the Audio Element OBU level, to provide the language code and/or the roles.

Note that there is a difference between providing language codes for indicating in which language are the annotations, vs. providing the language code of the audio content.

For the ISOBMFF binding, since the entire IA Sequence, possibly with multiple languages, is currently stored in a single track, we probably should provide guidance on how to set the track language (e.g. using the `mul` or `und` language code).

**Comment by sunghee-hwang** [comment]
@phill-williams @felicialim 
It would be worth you to review this and come up with a solution.
