### ISSUE TITLE
A Reserved OBU should be a part of either Descriptors or a Temporal Unit.

### ISSUE THREAD

**Issue by sunghee-hwang** [AOMediaCodec/iamf#793]
Based on the current spec, a Reserved OBU can be present at any location except the start of the IA Sequence.

If the V2 spec defines a new OBU, V1 writers will handle it as a Reserved OBU.
- When a Reserved OBU is present between Mix Presentation OBUs, v1 writes may misunderstand the end of Descriptors.
- When a Reserved OBU is present between Descriptors and the first Temporal Unit, it can be difficult for V1 writes to determine where the Reserved OBU is included.
- When a Reserved OBU is present between two Temporal Units, it can be difficult for V1 writes to determine where the Reserved OBU is included.

In this situation, the V1 decoder will not have a problem decoding it but the V2 decoders may have a problem decoding it correctly.

Here is a suggestion after a discussion with @jwcullen. 

When primary_profile or additional_profile is simple or base:
A Reserved OBU SHALL be regarded as either a part of Descriptors or a part of Temporal Unit with the following restrictions.
  - Reserved OBU SHALL not be present between MPOs.
  - A MPO will be the final descriptor OBU
  
And, we need to have an optional Temporal Delimiter OBU for the simple profile. (The current spec is prohibiting it)

**Comment by jwcullen** [comment]
Actually with that suggestion we may not actually need to add Temporal Delimiter OBUs to simple profile.

For more context I think this restriction is relevant in [§5.1.1](https://aomediacodec.github.io/iamf/#standalone-descriptor-obus) and [§6.2.3 `configOBUs` semantics](https://aomediacodec.github.io/iamf/#iasampleentry-section). Both these sections already impose an ordering on descriptor OBUs. 

Guaranteeing the placement of reserved descriptor OBUs vs reserved non-descriptor OBUs may help with backwards compatibility when parsing or manipulating IA Sequences.

e.g.
  - Transforming standalone IAMF to ISOBMFF-IAMF. When the standalone IAMF uses simple/base profile and reserved OBUs.

**Comment by jwcullen** [comment]
Oh I see why standalone IAMF with simple/base profile and reserved OBUs may need Temporal Delimiters.

If the reserved OBU should be grouped with a temporal unit it would be unclear which temporal unit it is grouped with.

If Temporal Delimiters were omitted there would be no distinction between Case 1 and Case 2. Including them allows these cases to be distinguished.

Case 1:
[Temporal Delimiter], Parameter_0, Parameter_1, Audio_frame_0, Reserved_X, 
[Temporal Delimiter], Parameter_0, Parameter_1, Audio_frame_0

Case 2:
[Temporal Delimiter], Parameter_0, Parameter_1, Audio_frame_0, 
[Temporal Delimiter], Reserved_X, Parameter_0, Parameter_1, Audio_frame_0
