### ISSUE TITLE
Selection of layout to use for pass-through rendering is ambiguous

### ISSUE THREAD

**Issue by felicialim** [AOMediaCodec/iamf#807]
[Section 7.3.2.1](https://aomediacodec.github.io/iamf/#processing-mixpresentation-rendering-m2l) says 

> Else, if there is an [Audio Element](https://aomediacodec.github.io/iamf/#audio-element) with a [loudspeaker_layout](https://aomediacodec.github.io/iamf/#loudspeaker_layout) that matches the playback layout, use it.

"it" could be ambiguous, referring to the Audio Element or the loudspeaker_layout. It should be the loudspeaker_layout. A proposed rewording is:

> - Else, if the [Audio Element](https://aomediacodec.github.io/iamf/#audio-element) has a [loudspeaker_layout](https://aomediacodec.github.io/iamf/#loudspeaker_layout) that matches the playback layout, use the layer with that matching [loudspeaker_layout](https://aomediacodec.github.io/iamf/#loudspeaker_layout).
>
> - Else, use the layer with the next highest available [loudspeaker_layout](https://aomediacodec.github.io/iamf/#loudspeaker_layout) compared to the playback layout.

**Comment by sunghee-hwang** [comment]
LGTM
