### ISSUE TITLE
Profile limitations with mixed-order ambisonics are ambiguous

### ISSUE THREAD

**Issue by jwcullen** [AOMediaCodec/iamf#808]
[§4.2 Base Profile](https://aomediacodec.github.io/iamf/#profiles-base) "SHALL be able to handle up to 18 channels."

[§3.6.3](https://aomediacodec.github.io/iamf/#syntax-ambisonics-config) implies up to 14th-order ambisonics is supported.

For full-order ambisonics it is clear than anything higher than 3rd-order would have too many channels to comply with base profile restriction.

For mixed-order ambisonics this could be read as permitting using higher order ambisonics (A17 - A224) as long as `substream_count + coupled_substream_count <= 18`. Is this intended?

Or is it intended that mixed-order ambisonics should only come from A0-15 when using simple/base profile?

**Comment by sunghee-hwang** [comment]
When ambisonics_mode = PROJECTION, the number of output channels after applying_demixing matrix is C (output channel count), and the C number of channels are input to IAMF Renderer. So,
- It can't be more than 16 for both simple and base.

In this sense, I don't think that v1.0 spec supports more than 3rd order.

**Comment by jwcullen** [comment]
Ok thanks. I thought that was the case. I missed this line in [§7.1](https://aomediacodec.github.io/iamf/#processing-ambisonics)

  > The output SHALL have N = [output_channel_count](https://aomediacodec.github.io/iamf/#output_channel_count) number of channels.
